.github/CODEOWNERS
=> CODEOWNERS: add initial list

c/README.md, c/ml-api-common.h, c/nnstreamer-single.h, c/nnstreamer.h, c/tizen_error.h
commit f5d1f9f8902ef4972acdae37861077e352a9a815 (HEAD -> doc/c, origin/doc/c)
Author: MyungJoo Ham <myungjoo.ham@samsung.com>
Date:   Tue Oct 13 19:52:00 2020 +0900
C/inference & common: imported Tizen 6.0 C-APIs
Imported Tizen 6.0 C-APIs from nnstreamer.git.
They will be kept duplicated until Tizen 6.5 devel starts
and it becomes ready for API package refactoring.
commit a8ace52c3a3e04907f4a658714301d1abb5350ff
Author: MyungJoo Ham <myungjoo.ham@samsung.com>
Date:   Tue Oct 13 19:51:32 2020 +0900
C/README: added platform info
Added which platforms are supported and how they are maintained.
=> Added initial files related with C-API / Inferences

java/android/build-nnstreamer-android-lib.sh, java/android/nnstreamer/build.gradle, java/android/nnstreamer/src/main/jni/Android-nnstreamer.mk, java/android/nnstreamer/src/main/jni/Android.mk
- Add `java/android/build-nnstreamer-android-lib.sh`
- Trim Android.mk and Android-nnstreamer.mk
- Set ML_API_VERSION
=> [JAVA/Android] Add android build script for nnstreamer @open sesame 03/22 11:25

packaging/machine-learning-api.spec
Add version information for Android ML API.
=> [Build] version info

.github/CODEOWNERS
add reviewers for API repository.
=> [Etc] add reviewers

java/android/build-nnstreamer-android-lib.sh, java/android/nnstreamer/src/main/jni/Android-flatbuf.mk, java/android/nnstreamer/src/main/jni/Android.mk, java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c
Update script to build Android lib with flatbuf and flexbuf subplugins.
=> [Android] sub-plugins for flatbuf/flexbuf

java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c
Change flatbuffers and flexbuffers subplugins name.
=> [Flatbuffers] Change subplugins name @open sesame 03/30 16:38 

tests/capi/unittest_capi_inference_nnfw_runtime.cc
change property name sync mode, nnstreamer will change sync mode and option.
=> [Test] change property name

.ahub/tcchecker-tca/config_android.yaml, .ahub/tcchecker-tca/config_tizen.yaml
Add TCM config filres for tizen and android.
=> [TCM] Add TCM config files

java/android/nnstreamer/build.gradle
Fix avas scan report, set junit ver 4.13.1.
=> [Android/Test] junit ver

packaging/machine-learning-api.spec
remove unnecessary feature definition and build requires.
=> [Tizen/Build] unnecessary build require

c/src/nnstreamer-capi-util.c
Fix indent style.
The "pointer" qualifier, '*', should be with the variable.
=> [Indent] Fix indent style

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
- Add a test for Flatbuf which checks eqaulity of input buffer with output of flatbuf decoder and converter
- input -> decoder -> other/flatbuf-tensor -> converter -> output
=> [Test/Flatbuf] Add Pipeline API test for Flatbuf

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
Code clean, remove unnecessary constructor in testcases.
=> [Android/Test] remove unnecessary constructor

java/android/build-nnstreamer-android-lib.sh, java/android/nnstreamer/src/main/jni/Android-tensorflow-lite.mk
update default version, tensorflow-lite v2.3.0 and nnfw v1.15.0.
=> [Android] update tf-lite and nnfw version

java/android/nnstreamer/src/main/jni/Android-tensorflow-lite.mk
- Add XNNPACK delegate in tensorflow-lite
- tensorflow-lite utilize XNNPACK as their default engine since v2.3.0
REF:
- https://github.com/google/XNNPACK
- https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/xnnpack
=> [Android/TFLite] Add XNNPACK delegate support

c/include/nnstreamer-capi-private.h, c/src/nnstreamer-capi-pipeline.c, c/src/nnstreamer-capi-util.c
Fixes #nnstreamer/2600
https://github.com/nnstreamer/nnstreamer/issues/2600
CC: @kparichay 
ps. This updates internal behaviors. No need for ACR.
=> Thread safety for ml_tensors_info APIs

c/include/nnstreamer.h, c/src/nnstreamer-capi-util.c
add new enum value (for AIFW and SLSI NPU)
=> [C-Api] enum for AIFW

c/include/nnstreamer.h, c/src/nnstreamer-capi-single.c, c/src/nnstreamer-capi-util.c
This patch adds NNFW Type for SRNPU.
Signed-off-by: Dongju Chae <dongju.chae@samsung.com>
=> [SRNPU/NNFW] Add NNFW Type for SRNPU

.gitignore
Add build directory to git ignore list.
=> [git] Add gitignore list @open sesame 6/7 15:15

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java
update docs to set custom option for tensorflow-lite model.
=> [Android] tf-lite custom options

java/android/build-nnstreamer-android-lib.sh
- Fix wget urls to support git lfs files
=> [android/build] Fix android build script for wget

java/android/nnstreamer/src/main/jni/Android.mk, java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c
Change nnfw feature definition in android build, same to c-api define.
=> [Android] nnfw feature

c/src/nnstreamer-capi-pipeline.c
- Unlock data when policy neither ML_PIPELINE_BUF_POLICY_AUTO_FREE nor ML_PIPELINE_BUF_POLICY_DO_NOT_FREE.
- Remove unreachable code
=> [Data] Unlock data and remove unreachable code

c/include/nnstreamer-capi-private.h, c/src/nnstreamer-capi-pipeline.c, c/src/nnstreamer-capi-util.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-customfilter.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-pipeline.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-singleshot.c, java/android/nnstreamer/src/main/jni/nnstreamer-native.h
Clone tensors-info handle and hold it in tensors-data handle.
Also, pass info handle to parse data object in Android native build.
=> [Api/TensorsData] hold tensors info in data handle

java/android/build-nnstreamer-android-lib.sh
Check target abi when build android library, and set dir name to get gstreamer prebuilt libs.
=> [Android/Build] check target abi

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/CustomFilter.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/Pipeline.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/SingleShot.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/TensorsData.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/TensorsInfo.java, java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-customfilter.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-pipeline.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-singleshot.c, java/android/nnstreamer/src/main/jni/nnstreamer-native.h
Prepare Java API on ubuntu, add feature for android and remove android annotation.
=> [Java] prepare ubuntu build @open sesame 06/23 19:10

java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/Pipeline.java, java/build-nnstreamer-android.sh, java/build-nnstreamer-ubuntu.sh
Add new script to build java library.
To prevent build error, mark prefix in java files and change it while building the library.
=> [Build/Java] add script to build jar

debian/control, debian/ml-inference-jni-wrapper.install, debian/rules
Add jni wrapper debian package.
=> [debian] Add jni wrapper debian package

c/src/nnstreamer-capi-util.c
Load framework priority from nnstreamer conf file.
=> [C-Api] framework priority from conf

c/include/nnstreamer-capi-private.h, c/include/nnstreamer.h, c/src/nnstreamer-capi-pipeline.c
Implement new API - appsrc callbacks.
=> [C-Api] implement src callback

c/src/nnstreamer-capi-pipeline.c, tests/capi/unittest_capi_inference.cc
Update caps for flexible tensor, old mime type for flex-tensor is removed.
=> [Test] update flex-tensor caps

tests/capi/unittest_capi_inference.cc
Add new testcases for src callback.
=> [Test/C-Api] src-callback test

java/android/nnstreamer/src/main/jni/Android.mk
clearly denote dependency to glib in android build.
=> [Android/Build] dependency to glib

java/android/build.gradle, java/android/nnstreamer/build.gradle, java/build-nnstreamer-android.sh
Remove release flag and related source.
Uploading library to jcenter is not available anymore.
=> [Android/Build] remove release flag

c/include/nnstreamer.h, c/src/nnstreamer-capi-util.c
Add new function to check hw availability with custom option string.
=> [C-Api] function to check hw availability

tests/capi/unittest_capi_inference.cc
Add checking nnfw availability util test.
=> [TEST] Add checking nnfw availability util test

README.md
- [Coverage] Set coverage badge
```
This patch enables coverage badge. Behind the scene, daily coverage
check is enabled :)
1. Build test: [ ]Passed [ ]Failed [X]Skipped
2. Run test: [ ]Passed [ ]Failed [X]Skipped
```
=> [Coverage] Set coverage badge

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java, java/android/nnstreamer/src/main/AndroidManifest.xml, java/android/nnstreamer/src/main/jni/Android-nnstreamer.mk, java/android/nnstreamer/src/main/jni/Android.mk, java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c, java/build-nnstreamer-android.sh
- Add MQTT support
- It requires paho.mqtt.c prebuilt lib
=> [android/mqtt] Add MQTT support

c/include/ml-api-service.h
Declaration of what the "ML Service APIs" will provide.
=> C/Service: introduction of the new API set.

c/src/ml-api-common.c, c/src/ml-api-inference-pipeline.c
- Remove unreachable code
- Remove unnecessary null check
REF:
https://analysishub.sec.samsung.net/service/analyses/985737
https://analysishub.sec.samsung.net/service/analyses/985799
=> [fix/trivial] Fix unreachable or unnecessary codes

c/src/ml-api-inference-internal.c, c/src/ml-api-inference-internal.h, c/src/ml-api-inference-pipeline.c, c/src/ml-api-inference-tizen-privilege-check.c, c/src/ml-api-internal.h
Commit 1: update error reporting API (more function)
Commit 2: elaborate messages of pipeline API & internal API
commit a293cca5c7902acea257d43c7e494a12722d5410 (HEAD -> capi/err6, fork/capi/err6)
Author: MyungJoo Ham <myungjoo.ham@samsung.com>
Date:   Wed Nov 17 17:58:34 2021 +0900
C/inference: more errors with elaborated messages.
Elaborate error and exception messages of pipeline API
and internal functions.
Use the new log/report infrastructure.
commit fab9e25cddeb6e77c411fc2b91ec08ad5fc5719d
Author: MyungJoo Ham <myungjoo.ham@samsung.com>
Date:   Wed Nov 17 17:58:02 2021 +0900
C/common: update error reporting macros
1. Error continue-report only if the op has returned a non-zero value.
2. Commonize formatting macro.
Signed-off-by: …
=> More errors with elaborated descriptions.

c/src/ml-api-inference-internal.c, c/src/ml-api-inference-internal.h, c/src/ml-api-inference-single.c
For the sake of app developers, let's elaborate error messages.
=> C/Single: elaborate error messages.

c/src/ml-api-inference-single.c
Allow to set NULL value for some properties such as custom, accelator
and the rest.
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
2. Run test: [ *]Passed [ ]Failed [ ]Skipped
=> [Single] Allow NULL value for some properties. 

c/src/ml-api-inference-single.c
- Remove unrechable code.
- Fix use after free.
=> [Single] Fix coverity issues

java/android/nnstreamer/src/main/jni/Android-tensorflow-lite.mk, java/build-nnstreamer-android.sh
- Add tflite v2.7.0 support
- Set v2.7.0 as default version of tflite
=> [android/tflite] Add tflite v2.7.0 support

tests/capi/unittest_capi_inference.cc
Add replacing string test.
(Copied from nnstreamer/nnstreamer/tests/unitest_util.c)
=> [TEST] Add replacing string test

c/include/ml-api-common.h, c/include/ml-api-service-internal.h, c/include/ml-api-service.h, c/include/nnstreamer.h, c/src/ml-api-service-private.h
This is the start of designing https://github.com/nnstreamer/nnstreamer/issues/3473
Phase 1 APIs are declared.
=> C/Service: first prototypes of service API Phase 1

tests/capi/unittest_capi_inference.cc
Check whether the allowed elements are properly handled or not.
Related issue: https://github.com/nnstreamer/nnstreamer/issues/3252
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
2. Run test: [ *]Passed [ ]Failed [ ]Skipped
=> [TEST] Check allowed elements.

c/src/ml-api-inference-internal.h, c/src/ml-api-inference-pipeline.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-pipeline.c
Add util function to get gst-element instance.
=> [C-Api/Util] util function to get gst element @open sesame 01/25 17:47

packaging/machine-learning-api.spec
Add gcov package for tizen coverage auto measurement tool.
=> [Tizen/TEST] Add gcov package

c/src/ml-api-inference-internal.c, c/src/ml-api-inference-pipeline.c, c/src/ml-api-inference-single.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-customfilter.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-pipeline.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-singleshot.c, java/android/nnstreamer/src/main/jni/nnstreamer-native.h
The log util was separated from nnstreamer repo.
Remove unnecessary header and update log util.
=> [Log] log utils from nnstreamer

c/src/ml-api-inference-internal.c, c/src/ml-api-inference-pipeline-internal.h, c/src/ml-api-inference-pipeline.c
To increase both readability and maintainability, this PR does refactoring applying the below techniques.
* Move Method
* Decompose Conditional
* Substitute Algorithm
* First draft
* Add note tag that the index of ml_tensor_type_e should be equal to that of tensor_type.
* Add error message in case of invalid type conversion
=> [Refactoring] Increase readability and maintainability

c/capi-ml-inference-pipeline.pc.in, c/capi-ml-inference-single.pc.in, c/meson.build, debian/control, debian/ml-api-common-dev.install, debian/ml-api-common.install, debian/ml-inference-api-dev.install, debian/ml-inference-api.install, debian/ml-inference-pipeline-api.install, debian/ml-inference-pipeline-dev-api.install, debian/ml-inference-single-api.install, debian/ml-inference-single-dev-api.install, packaging/machine-learning-api.spec
- Separate single/pipeline debian package
- Change library name (capi-nnstreamer-* -> ml-inference-*)
=> [debian] Separate debian packaging

c/include/ml-api-common.h, c/include/ml-api-service-internal.h, c/include/ml-api-service.h, c/meson.build, c/src/ml-api-service-private.h, tests/capi/unittest_capi_service.cc
cleanup headers and warning in meson build script before starting ACR process.
=> [CodeClean] cleanup headers

tests/capi/unittest_capi_service.cc
To remove duplicate code in each test case, this patch applies the
test fixture framework. g_autofree macro is used for allocated space
to be freed automatically no matter test case is passed or not.
* Update the code to comply with coding style.
* Apply test fixture framework of Google Test
=> [C-API/Test] Apply test fixture to remove duplicate code

c/src/ml-api-common.c
Tell the API users why the error happens and how they can mend it.
Fixes https://github.com/nnstreamer/nnstreamer/issues/3562
=> C/common: ml_tensors_info_set_tensor_dimension error message.

.github/CODEOWNERS
New members introduced: @songgot (will be writing APIs soon)
=> CODEOWNERS: update reviewers.

c/include/ml-api-service.h
Under the API review, update API description and example code.
=> [C-Api/Service] update API description

c/src/ml-api-common-tizen-feature-check.c, c/src/ml-api-common.c, c/src/ml-api-inference-pipeline.c, c/src/ml-api-inference-single.c, c/src/ml-api-internal.h, c/src/ml-api-service-db.cc
Add machine learning service feature check function.
=> [Feature] Add ml-service feature check function

c/src/ml-api-service-db.cc
Fix svace issue - remove memory leak.
=> [C-Api/Service] fix svace issue

debian/changelog, java/android/nnstreamer/src/main/jni/Android.mk, meson.build, packaging/machine-learning-api.spec
Set project version to 1.8.1 (will be updated later - 1.8.2 for Tizen M2)
=> [ML-API] version info

c/doc/nnstreamer_doc.h, c/include/ml-api-service.h
This patch adds the doxygen section and updates doc.h file for ML Service API.
=> [C-API] Update doc file for ML Service API

c/src/ml-api-inference-pipeline.c
1. Clear element callback before changing the pipeline state - receiving the EOS event.
2. Fix element lock when an error occurs in internal process.
=> [C-Api/pipeline] clear element callback

c/src/ml-api-common-tizen-feature-check.c, c/src/ml-api-common.c, c/src/ml-api-inference-pipeline-internal.h, c/src/ml-api-inference-pipeline.c, c/src/ml-api-inference-single.c, c/src/ml-api-inference-tizen-privilege-check.c, c/src/ml-api-service-db.cc, tests/capi/unittest_capi_service_db_mock.cc
- Fix some typos in several files
=> [trivial] Fix some typos

c/src/ml-api-common.c, c/src/ml-api-inference-pipeline.c
To increase maintainability and readability, this PR applies the below techniques.
- Cleanup the nested-if statement
- Apply the extract method technique to remove redundant code
- Remove unnecessary NULL assignment
=> [C/Inference] Refactoring the inference API for maintainability

c/meson.build, c/src/ml-api-inference-internal.c, c/src/ml-api-inference-internal.h, c/src/ml-api-inference-single-internal.h, c/src/ml-api-inference-single.c, meson.build
Remove gst dependency from singlep-shot.
Build test: [ *]Passed [ ]Failed [ ]Skipped
Run test: [ *]Passed [ ]Failed [ ]Skipped
=> [Single] Remove gst dependency from single-shot 

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java, java/android/nnstreamer/src/main/jni/Android-nnstreamer-prebuilt.mk, java/build-nnstreamer-android.sh
1. add version flag and update prebuilt library for mxnet.
2. disable test when building lite version.
=> [Android] update script for mxnet

c/include/ml-api-common.h, c/include/nnstreamer-single.h, c/include/nnstreamer.h
Prepare ACR, review native API and update description.
=> [C-Api] update API description

c/include/ml-api-common.h, c/src/ml-api-inference-single.c, tests/capi/unittest_capi_inference_single.cc
Prepare ACR, add new NNFW type (TVM) and mark Tizen version.
=> [C-Api] add NNFW type (TVM)

c/include/ml-api-common.h
- Fix API descriptions to meet the design guide.
=> [doc] Fix API header description

daemon/includes/dbus-interface.h, daemon/meson.build, daemon/pipeline-module.c, dbus/machine-learning-agent.conf.in, dbus/pipeline-dbus.xml
- Add and implement the pipeline related feature.
- It supports following dbus method call:
- register_pipeline
- start_pipeline
- stop_pipeline
- destroy_pipeline
- get_state
- get_description
=> [Agent] Add pipeline feature to the daemon

tests/capi/unittest_capi_inference_nnfw_runtime.cc
This patch applies the Google Test Fixture to the unit test of NNFW
Inference MLAPI test. It removes the duplicate codes such as finalizing
the handle of TensorsInfo, TensorsData, Single, and Pipeline in each
test case. As a result, it helps developers focus on the test case
scenario without considering trivial settings such as model loading,
or memory allocation.
* Remove global mutex and count variable
* Fix the memory leak
* Cleanup the source code such as unnecessary line, omitted `static` flag
* Initialize class member variables to prevent svace issue.
* Apply Google Test Fixture
* Remove the duplicate codes in each test case
=> [Refactoring] do refactoring the NNFW unit test to improve maintainability @open sesame 08/03 10:44

debian/control, debian/ml-api-unittests.install, debian/rules, packaging/run_unittests.sh
- Enable test on ubuntu build.
=> [Debian] Enable test on ubuntu build

dbus/machine-learning-agent.conf.in
- Change the owner to "service_fw".
- Set default deny for default context.
=> [agent] Update policy conf file

tests/capi/unittest_capi_service_agent_client.cc
- Set available port number for service API unittest, rather than
default value
=> [test/service] Set available port number for service API unittest

packaging/machine-learning-api.spec
Clearly check unittest flag when building tizen rpms.
=> [Build] flag to run unittest

daemon/includes/log.h, daemon/meson.build
Add dlog dependency when building daemon on Tizen release.
=> [Build] dependency to dlog

c/include/ml-api-service.h
- Add signatures of two APIs for query_client service
=> [service] Add API header for query_client service

.TAOS-CI/.gbs.conf
- Update repo urls to the new one.
=> [conf] Update gbs conf to new repos

c/src/ml-api-service-query-client.c
Fix svace issue, mem leak case.
=> [Svace] fix res leak

c/src/ml-api-service-common.c, tests/capi/unittest_capi_service_agent_client.cc
- Fix mem leaks in query client and its unittests
=> [query] Fix mem leaks in query client @open sesame 09/19 10:45

c/src/ml-api-service-query-client.c
- Check return values in sink callback
=> [coverity] Check return value in query_client cb

daemon/pipeline-module.cc
- Fix return values of method to TRUE cause all the call is success
- This fix recent ASAN issue
=> [agent] Fix return value of dbus method invoc

tests/capi/unittest_capi_service_agent_client.cc
- Add more negative testcases for ml-service APIs
=> [test] Add more negative testcases for ml-service APIs

packaging/machine-learning-api.spec, tests/capi/unittest_capi_datatype_consistency.cc, tests/capi/unittest_capi_inference.cc, tests/capi/unittest_capi_inference_single.cc
1. Fix invalid test name, to run unittest of data utils.
2. Code clean, add more negative testcases.
=> [Test] update test

c/src/ml-api-common.c
Code clean, update feature name (same with nnstreamer repo) and size of float16 type.
=> [C-Api] feature for float16 type

c/src/ml-api-service-agent-client.c, c/src/ml-api-service-query-client.c
Code clean, clearly check returned error code of ML API.
=> [C-Api/Service] clearly check returned errcode

tests/capi/unittest_capi_inference.cc
- Initialize tensors info to fix build warning
=> [TEST] Initialize tensors info

c/src/ml-api-common.c
Fix mem leak case when failed to create data handle.
=> [Common] mem leak case

c/meson.build, c/src/meson.build, daemon/meson.build, meson.build, tests/capi/meson.build, tests/capi/unittest_capi_inference_single.cc
Code clean, declare dependency to common library and cleanup meson script.
=> [Meson] cleanup dependencies to common library

daemon/meson.build, meson.build
Code clean to build ml-service,
- fix dependency to gio library.
- remove unnecessary declaration in meson script.
=> [Meson] dependency to build ml-service

tests/capi/unittest_capi_service_agent_client.cc
Fix double free case in ml-service testcases.
=> [Test] fix double free case

daemon/includes/dbus-interface.h, daemon/includes/test-dbus-interface.h
Set exact signal name for ml-service daemon.
=> [Service] fix signal name

c/src/ml-api-inference-internal.h, c/src/ml-api-service-query-client.c
Fix typo and build error on olb ubuntu.
=> [Build] error on old ubuntu

packaging/machine-learning-api.spec
Exclude test related gcno files from gcov package.
=> [gcov] Exclude test gcno files

tests/capi/unittest_capi_service_agent_client.cc
Set feature state after all testcases are done.
=> [Test] feature state in tizen test

c/include/nnstreamer.h
Fix typo in sample code for custom easy filter.
=> [C-Api] fix typo

c/src/ml-api-service-agent-client.c, c/src/ml-api-service-common.c
Check returned val and handle error case when failed to invoke dbus methods.
=> [Service] handle dbus error case

c/src/ml-api-inference-single.c
Prevent error case - null data ptr in invoke thread.
=> [C-Api/Single] invalid data handle in invoke thread @open sesame 01/26 17:26

meson.build, packaging/machine-learning-api.spec
Add dependency to sqlite and cleanup, mark todo to remove leveldb for future work.
=> [Service] dependency to sqlite

c/src/ml-api-inference-single.c
Prevent error case - null data ptr in invoke thread.
* https://github.com/nnstreamer/api/commit/46ef6086c1286fd30d020b5813b7253558a79db1
* https://code.sec.samsung.net/jira/browse/TSEVEN-4660
=> [C-Api/Single] invalid data handle in invoke thread

daemon/service-db.cc
Code clean, handle error case in service-db.
=> [Service/CodeClean] handle error case

c/src/ml-api-common.c
This fixes https://github.com/nnstreamer/nnstreamer/issues/4015
that didn't give appropriate error messages.
=> c-api: Update API error messages

c/include/ml-api-service.h, c/src/ml-api-service-agent-client.c, c/src/ml-api-service-common.c, c/src/ml-api-service-private.h, daemon/includes/dbus-interface.h, daemon/model-dbus-impl.cc, tests/capi/unittest_capi_service_agent_client.cc
- Add callback for the new API in the daemon impl.
- Add initial impl for the C-API.
- Add a simple TC using API `ml_service_model_register`
=> [After #248] Initial commit for the new ml-service API `ml_service_model_register`

c/src/ml-api-common.c, c/src/ml-api-inference-single.c, c/src/ml-api-internal.h, tests/capi/unittest_capi_inference.cc
These patch set are the hotfix from main branch related with Tizen 7.0 DA GBM Release.
All patches are already tested.
=> Hotfix from main branch

daemon/includes/pkg-mgr.h, daemon/main.c, daemon/meson.build, meson.build
Fix build error on ubuntu, dependency to pkgmgr.
=> [Build] dependency to pkgmgr on ubuntu

daemon/includes/service-db.hh, daemon/service-db.cc
Code clean, sepatate method to initialize ml-service database.
=> [Service/CodeClean] separate method to init database

daemon/meson.build, debian/control, meson.build, packaging/machine-learning-api.spec
Change database to sqlite, remove dependency to leveldb.
=> [Build] remove dependency to leveldb

debian/rules, packaging/machine-learning-api.spec, tests/capi/unittest_capi_inference.cc, tests/capi/unittest_capi_inference_latency.cc, tests/capi/unittest_capi_inference_nnfw_runtime.cc, tests/capi/unittest_capi_inference_single.cc, tests/meson.build
Fix name to root directory, use prefix 'MLAPI_'.
=> [Test] name to root directory

daemon/service-db.cc
Handle table version. If table schema is changed, we should implement data migration later.
=> [Service] handle table version

c/include/ml-api-common.h, c/include/ml-api-service.h, c/src/ml-api-service-agent-client.c, tests/capi/unittest_capi_service_agent_client.cc
Define new function and info handle for machine learning models.
=> [Service/Model] define new API

c/src/ml-api-service-agent-client.c, daemon/service-db.cc
Code clean, handle res-leak if error occurs.
=> [CodeClean] handle error case

daemon/service-db.cc
- Use `sqlite3_bind_text` instead of formatted string to prevent sql injection attack.
=> [agent/DB] Prevent sql injection by using `sqlite3_bind_text`

packaging/machine-learning-api.spec, tests/daemon/meson.build, tests/daemon/unittest_service_db.cc, tests/meson.build
- Add negative unittest for serviceDB.
=> [test] Add service db test

tests/capi/unittest_capi_service_agent_client.cc
- Add some negative test for ml-agent.
=> [test] Add some negative test for ml-agent

daemon/model-dbus-impl.cc
Use common log util in model-dbus impl.
=> [Service] common log util

daemon/model-dbus-impl.cc
Init-zero to connect the signals of model-dbus.
=> [Service] init handle id

daemon/gdbus-util.c, daemon/main.c, daemon/model-dbus-impl.cc, daemon/modules.c, daemon/pipeline-dbus-impl.cc, daemon/pkg-mgr.c, daemon/service-db.cc, tests/meson.build
Trivial, fix indent and init null to global val.
=> [CodeClean] fix indent

daemon/includes/log.h
- Let ml-agent logs be more verbose in Tizen.
=> [agent] Change tizen log functions of ml-agent

meson.build, tests/capi/meson.build, tests/meson.build
This patch revises the meson build scripts related to the test sub-directory.
=> Tests/Meson: Revise meson build scripts in tests

c/src/ml-api-service-agent-client.c, daemon/includes/service-db.hh, daemon/model-dbus-impl.cc, daemon/service-db.cc, dbus/model-dbus.xml, tests/capi/unittest_capi_service_agent_client.cc, tests/daemon/unittest_service_db.cc
- Add a new column "app_info" to the service DB's tblModel table.
- This app_info will be json string consists of tizen application information which owns model.
=> [service] Add "app_info" column to the model DB

meson.build
- Add an empty build dep for tizen appfw, used by servce API
=> [build] Add empty build dep for tizen appfw for local build/test

c/src/meson.build, daemon/meson.build, meson.build
Code clean, define dependencies to tizen packages.
=> [Meson] dependency to tizen pkgs

tests/meson.build
Use predefined dependencies in meson script.
=> [Test/Meson] common dependency

daemon/pkg-mgr.cc
- Fix memleak of pkg_info
- Change variable name not to hide the parameter of cb
=> [CodeClean] Fix coverity issues

c/src/ml-api-common.c
Code clean, remove duplicated code.
=> [C-Api/CodeClean] remove duplicated code

daemon/includes/service-db.hh, daemon/service-db.cc, tests/daemon/unittest_service_db.cc
Fix invalid table schema and cleanup service-db test.
=> [Service] invalid table schema

c/include/ml-api-common.h
Update API description, fix design guide.
=> [C-Api] Tizen API guide

daemon/service-db.cc, tests/daemon/unittest_service_db.cc
Raise exception when given version number is 0.
=> [Service] handle invalid version @open sesame 05/03 09:30

c/src/ml-api-service-common.c, c/src/ml-api-service-private.h, daemon/pkg-mgr.cc
Code clean,
1. fix indent and remove unnecessary lines.
2. replace function to compare pkg type (case-insensitive).
=> [C-Api/CodeClean] remove unnecessary code

daemon/pipeline-dbus-impl.cc
The ID from pipeline hashtable in daemon is internal value. This PR hides this internal ID value.
=> [Service/Log] printing internal value

daemon/includes/service-db.hh
Fix build error, clang-format of service-db.
=> [Build/Service] fix indent

daemon/service-db.cc
Code clean, use common logutil in service-db.
=> [Service] logutil in service-db

daemon/includes/service-db.hh, daemon/service-db.cc
Code clean, add internal util function for DB transaction.
=> [Service] functions for transaction

packaging/run-unittest.sh
Fix script for coverage auto measuremnt
- Change directory before run the tests.
=> [Tizen] Fix script for coverage auto measurement

c/include/ml-api-common.h, c/include/ml-api-service.h, c/src/ml-api-internal.h, debian/changelog, packaging/machine-learning-api.spec
- Tizen X.5 is not going to be used. Change tizen 7.5 to tizen 8.0
=> [Release] Change the name tizen 7.5 into tizen 8.0

c/capi-ml-service.pc.in, c/meson.build
This patch fixes the wrong requires section of ML Service package config file.
=> [Service] Fix the wrong requires section of pkgconfig file

daemon/includes/service-db.hh, daemon/service-db.cc, tests/capi/unittest_capi_service_agent_client.cc, tests/daemon/unittest_service_db.cc
Add util functions in service-db,
1. prevent deleting activated model,
2. add util function to check model registration.
=> [Service] deleting activated model

c/src/ml-api-service-agent-client.c
This patch eliminates null-checks for the output parameters, which require memory allocation at the callee side.
=> API/Client: Revise null-checks for output parameters 

c/src/ml-api-service-agent-client.c
g_new0 would not work as the author intended. This patch replaces g_new0 macros with g_try_new0 macros so that memory allocation failure is checked at runtime.
=> API/Client: Replace g_new0 with g_try_new0

c/src/ml-api-service-agent-client.c
This is a trivial patch for code cleaning. Toward better readability, nested scope and g_auto* are used for JSON handling.
=> API/Client: Use nested scope for JSON handling 

c/src/ml-api-service-agent-client.c
Code clean, use common log-util in ml-agent code.
=> [Service] common log-util

tests/capi/unittest_capi_inference_latency.cc, tests/capi/unittest_capi_inference_nnfw_runtime.cc
Enable testcase if tensorflow-lite ver2.x is available.
=> [Test] feature for tf-lite

c/src/ml-api-service-agent-client.c
This patch revises the mechanism that creates ml_option_h typed data from a JSON cstring.
=> API/Client: Revise JSON cstring conversion code

c/src/ml-api-service-agent-client.c
error param should be paased to 'json_parser_load_from_data' since error_report acess to error message.
=> fix svace issue. @open sesame 6/14 14:17

c/src/ml-api-inference-single.c
- Destroy ml_tensors_info_h in ml_single_close
- Call gst_tensors_info_free
=> [fix] Fix mem leak in Single API

c/src/ml-api-inference-single.c
- Change size_limit to rank_limit in rank related methods
=> [single] Fix macro value for rank

c/src/ml-api-service-agent-client.c
Code clean, add internal function to check the path of model or resource. This will be used resource-add function later.
=> [C-Api] util to check file path

daemon/model-dbus-impl.cc
Set exact complete function in dbus callback.
=> [Service] set dbus-complete function

daemon/gdbus-util.c, daemon/gdbus-util.h, daemon/model-dbus-impl.cc, daemon/pipeline-dbus-impl.cc, tests/dbus/test-dbus-impl.c
Fix log message, and add common function to initialize gdbus module.
=> [Service] util to init gdbus module

daemon/service-db.cc, daemon/service-db.hh
Code clean,
1. Add methods in service-db to reduce duplicated code.
2. Add key prefix for each table.
=> [Service/CodeClean] reduce duplicated code

daemon/service-db.cc, daemon/service-db.hh, tests/daemon/unittest_service_db.cc
Add new table for ml-resource, and add functions for ml-agent.
=> [Service] add resource table

c/src/ml-api-service-private.h, daemon/dbus-interface.h, daemon/include/ml-agent-dbus-interface.h, daemon/meson.build, daemon/ml-agent-dbus-interface.c, daemon/resource-dbus-impl.cc, dbus/meson.build, dbus/resource-dbus.xml, tests/capi/unittest_capi_service_agent_client.cc
Implement ml-agent interface for ml-resource.
=> [Service] ml-agent interface for resource

tests/capi/unittest_capi_service_agent_client.cc
Code clean, use predefined dbus name in dbus-interface.
=> [Test] predefined dbus name

c/include/ml-api-common.h, c/include/ml-api-service.h, c/src/ml-api-service-agent-client.c, tests/capi/unittest_capi_service_agent_client.cc
Define new API set for ml-resource control.
=> [C-Api/Service] define API for ml-resource

c/src/ml-api-service-agent-client.c
Code clean, return val if failed to parse app-info from json string.
=> [Service] return val to parse app info

c/src/ml-api-common.c, c/src/ml-api-internal.h, tests/capi/unittest_capi_service_agent_client.cc
Add internal util function to create ml-information-list handle.
TODO:
I will update another PR to cleanup info-list handle in ml-agent.
=> [Common] util to create info-list handle

c/src/ml-api-service-agent-client.c
Define internal common function to get app info.
TODO:
New field for app info for ml-resource and the funtion adding ml-resource will be udpated.
=> [Service] util to get app info

tests/capi/unittest_capi_service_agent_client.cc
Update testcase to use ml-resource API.
=> [Service/Test] add test about ml-resource

c/src/ml-api-service-agent-client.c, daemon/include/ml-agent-dbus-interface.h, daemon/ml-agent-dbus-interface.c, daemon/resource-dbus-impl.cc, daemon/service-db.cc, daemon/service-db.hh, dbus/resource-dbus.xml, tests/capi/unittest_capi_service_agent_client.cc, tests/daemon/unittest_service_db.cc
Add new field app_info for tizen RPK install case, to manage app-information like model API.
=> [Service] handle app-info for ml-resource

c/src/ml-api-common.c, c/src/ml-api-inference-internal.c
Code clean, condition to release mem-block and add missed tag.
=> [CodeClean] missed tag

c/src/ml-api-service-agent-client.c
Use common function to parse app-info and update ml-information handle.
=> [Service] util to parse app-info

daemon/pkg-mgr.cc
Code clean, add util to get app-info string and reduce duplicated code.
=> [CodeClean/Service] util to get app-info

c/src/ml-api-inference-tizen-privilege-check.c
Code clean, get the element name from tizen media config and replace it.
TODO: handle properties for each element.
=> [Pipeline] element name for tizen media src

c/src/ml-api-inference-single.c
Code clean, fix svace issue. Remove unnecessary log - data type.
=> [CodeClean] delete unnecessary log

c/src/ml-api-inference-internal.c
Check null case when getting nth info of ml and gst tensor-info.
=> [Svace] fix svace issue

c/src/ml-api-common.c
Code clean, check index in tensors-info handle and update log message.
=> [C-Api] check index in tensors-info handle

c/src/ml-api-inference-pipeline.c
Code clean, update code to get nth gst-info.
=> [C-Api] function to get nth gst-info

daemon/pkg-mgr.cc
Code clean, define function to parse json file in rpk, including resource and pipeline update.
=> [CodeClean/Service] parse json in rpk

.github/workflows/gbs_x64.yml, .github/workflows/tizen.gbs.conf
Add gbs build github action for ml-api and nntrainer
=> [Github Action] Add gbs build for ml-api and nntrainer @open sesame 08/17 11:49

c/src/ml-api-common.c, c/src/ml-api-internal.h, tests/capi/unittest_capi_inference_single.cc
Prevent invalid function call.
Add type of ml-information handle and macro to check the handle.
=> [C-Api] type of ml-information handle

c/src/ml-api-inference-pipeline.c
[C-API] Bugfix for ml_pipeline_element_get_handle
Need to ref element obtained by iterate_element() and unref it in cleanup_node() for common_elem
- common_elem by ml_pipeline_element_get_handle() need to unref in cleaunup_node() because g_hash_table_lookup assign new memory.
but normal operation, unref is not necessary, so add ref in iterate_element()
- Now, the element's finalize function is called after ml_pipeline_element_get_handle()
=> [C-API] Bugfix for ml_pipeline_element_get_handle

packaging/machine-learning-api.spec
Disable nnstreamer-edge on TV profile.
=> [Tizen] disable nns-edge on TV profile. @open sesame 09/11 17:52

c/src/meson.build, meson.build, packaging/machine-learning-api.spec, tests/capi/meson.build
Add feature and enable remote-service when curl and nnstreamer-edge is available.
=> [Build] dependencies to nns-edge and curl

debian/changelog, java/android/nnstreamer/src/main/jni/Android.mk, meson.build, packaging/machine-learning-api.spec
Update version to 1.8.4, Tizen 8.0 M2 release.
=> [Release] update version

debian/changelog, java/android/nnstreamer/src/main/jni/Android.mk, meson.build, packaging/machine-learning-api.spec
Update version, start implementation for next release.
=> [Release] start impl for next release

tests/capi/meson.build
- Add service_dep dependency to service related unittests.
=> [test] Add missing deps for service unittests

c/include/ml-api-common.h, c/include/ml-api-service.h, c/include/nnstreamer-tizen-internal.h, c/include/nnstreamer.h
Code consistency, add tag in return val field.
=> [Doc] add const tag

c/src/ml-api-service-query-client.c
Use 'caps' property in appsrc, not caps-filter.
=> [C-Api/Query] use caps property

c/src/ml-api-inference-single.c
Add key to get the neural network name from ml-option.
=> [C-Api] option to get framework

c/src/meson.build, daemon/include/meson.build, daemon/meson.build, daemon/ml-agent.pc.in, packaging/machine-learning-api.spec, tests/capi/meson.build, tests/daemon/meson.build, tests/meson.build
This patch changes the name of ML-Agent from ml-agentd to ml-agent.
=> MLAgent: Change the name of ML-Agent

daemon/service-db.cc
There is some timing issue to save the changes in DB, set trasnsation for INSERT/UPDATE command.
=> [ml-service] Set transaction

c/src/ml-api-common.c, c/src/ml-api-inference-single.c, c/src/ml-api-internal.h, daemon/service-db.cc
We implemented 0-initialized dimension in nnstreamer.
Remove unnecessary rank list from single handle.
=> [C-Api/Single] remove rank list

c/include/nnstreamer-tizen-internal.h, c/src/ml-api-service-remote.c, tests/capi/unittest_capi_remote_service.cc
- Add remote service event callback
=> [ml-service] Add remote service event callback @open sesame 11/16 19:46

c/src/ml-api-inference-single.c
Use gst-info and create handle inside of single-shot instance.
Referencing struct does not initialize lock and other variables.
=> [C-Api/Single] create in/out handle in single-shot

c/src/ml-api-common.c, c/src/ml-api-inference-pipeline.c, c/src/ml-api-inference-single.c, c/src/ml-api-internal.h, c/src/ml-api-service-query-client.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c
Code clean, use GstTensorMemory struct defined in nnstreamer.
=> [Common/CodeClean] struct for tensor memories

java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java
sync to native API, update max rank and tensor size limit.
=> [Java] max rank and tensor limit

c/src/ml-api-common.c, c/src/ml-api-inference-internal.c, c/src/ml-api-inference-internal.h, c/src/ml-api-internal.h, java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c, tests/capi/unittest_capi_inference.cc
Use gst-info struct and util functions from nnstreamer.
Remove unnecessary functions for ml-info.
=> [C-Api] use tensor-info struct from nns

c/src/ml-api-common.c, tests/capi/unittest_capi_inference.cc
Check invalid dimension case before updating tensor-info handle.
=> [C-Api/Common] check invalid dimension

daemon/pkg-mgr.cc
Parse clear field from json, to delete old model or resource from database.
=> [Service] clear flag to delete old model

c/src/ml-api-service-remote.c
Fix svace issue, change data type to get the path from ml-option.
=> [CodeClean] fix svace issue

tests/capi/unittest_capi_inference_single.cc
Sync to tct, update testcase - change model dimension.
=> [Test] update testcase - set_info

java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-customfilter.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-pipeline.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-singleshot.c
Create extended handle for max rank limit 16 in java native code.
=> [Java] create extended tensor-info

c/meson.build, c/src/meson.build, debian/control, meson.build, packaging/machine-learning-api.spec
Update pkg dependency to nnstreamer library.
=> [Pkg] update dependency to nns library

tests/capi/unittest_capi_inference_single.cc
We will remove tf-lite ver1.x on tizen release, fix related testcase.
=> [Test] testcase with tf-lite ver1.x

.TAOS-CI/.gbs.conf
- Change url from Tizen to Tizen-8.0
=> [lts][gbs] Fix gbs repo url to Tizen-8.0

c/src/ml-api-inference-single.c
Set in/out data handle those are passed to invoke thread, also clearly release data when closing the thread.
=> [C-Api/Single] data handle passed to invoke thread

c/src/ml-api-common.c
Fix invalid casting after allocating option handle.
=> [C-Api] invalid casting of ml-option

tests/capi/unittest_capi_service_agent_client.cc
Add pre/post condition for test, clear test data after unittest is finished.
=> [Test] test condition

c/src/ml-api-service-agent-client.c, c/src/ml-api-service-common.c, c/src/ml-api-service-query-client.c, tests/capi/unittest_capi_service_agent_client.cc
Code clean, update param name (sync to public header) and check null param.
=> [C-Api] sync param to public header

java/build-nnstreamer-android.sh
Remove presonal alias from the build script.
=> Android build fix: ll is a personal alias

daemon/ml-agent-interface.c
Temporal bug fix before removing ml-agent from api repo.
Fix invalid handle type and check return ptr for gerror.
=> [Agent] invalid handle type

c/src/ml-api-common.c, c/src/ml-api-internal.h, c/src/ml-api-service-agent-client.c, tests/capi/unittest_capi_inference_single.cc, tests/capi/unittest_capi_service_agent_client.cc
Code clean, check empty string case.
=> [C-Api] check empty key value

c/src/ml-api-service-agent-client.c, c/src/ml-api-service-query-client.c, c/src/ml-api-service-remote.c
1. set null after releasing priv data in service handle.
2. remove unnecessary param in query priv data.
=> [CodeClean/Service] set null after free priv data

c/include/ml-api-common.h, c/include/nnstreamer.h, c/src/ml-api-common.c, c/src/ml-api-internal.h, tests/capi/unittest_capi_inference.cc
Add new util functions,
1. clone tensor-data handle.
2. get tensors-info of tensor data frame.
This requires ACR for public release.
=> [Util] public function for tensor-data

tests/capi/unittest_capi_remote_service.cc, tests/capi/unittest_capi_service_agent_client.cc
Code clean, remove unnecessary param - bus type to run agent in testcase.
=> [Test] remove unused param

c/src/ml-api-service-extension.c
Code clean, use internal util function to create and copy tensor info handle.
=> [C-Api] use util function to copy tensor info

c/include/ml-api-service.h, c/src/ml-api-service-agent-client.c, c/src/ml-api-service-extension.c, c/src/ml-api-service-remote.c, tests/capi/unittest_capi_remote_service.cc, tests/capi/unittest_capi_service_agent_client.cc
Update API name prefix - ml_service_pipeline.
=> [C-Api/Service] update ml-service pipeline

java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/TensorsInfo.java
This patch allows 0 value dimension in setDimension function.
https://github.com/nnstreamer/nnstreamer/pull/4111
=> [Java] Allow 0 value dimension

c/src/ml-api-common.c, c/src/ml-api-inference-pipeline.c, c/src/ml-api-inference-single.c
Code clean, remove unnecessary code to create info handle for internal usage.
=> [C-Api] unnecessary info handle

meson.build, tests/capi/unittest_capi_remote_service.cc, tests/capi/unittest_capi_service_agent_client.cc, tests/capi/unittest_capi_service_extension.cc
Add definition to get the install prefix to run the ml-agent for unittest.
=> [Test] ml-agent install prefix

tests/capi/unittest_capi_service_extension.cc
Fix wrong logical operator to break the loop.
=> [TEST] Fix wrong logical operator @open sesame 04/04 14:26

c/include/ml-api-service.h, c/src/ml-api-service-agent-client.c, c/src/ml-api-service-offloading.c, c/src/ml-api-service.c
Code clean, fix svace issues and remove unnecessary code.
=> [CodeClean] fix svace issues

packaging/machine-learning-api.spec
=> [armnn] Remove armcl dependency

packaging/machine-learning-api.spec
Remove armcl dependency from Tizen 8.0
=> [armnn] Remove armcl dependency from 8.0

c/src/ml-api-service-offloading.c, c/src/ml-api-service-offloading.h, c/src/ml-api-service-private.h, tests/capi/unittest_capi_service_offloading.cc
Code clean, remove unnecessary code and update log before updating internal function (related to ml-offloading).
=> [CodeClean] remove unnecessary code

c/src/ml-api-service-offloading.c, c/src/ml-api-service-offloading.h, c/src/ml-api-service-private.h, c/src/ml-api-service-training-offloading.c, c/src/ml-api-service-training-offloading.h, c/src/ml-api-service.c, packaging/machine-learning-api.spec
Code clean, update function name for offloading and fix svace issues.
=> [Service] fix svace issues

tests/capi/unittest_capi_service_agent_client.cc, tests/capi/unittest_capi_service_extension.cc, tests/capi/unittest_capi_service_offloading.cc, tests/capi/unittest_capi_service_training_offloading.cc
Code clean,
1. remove unnecessary header and precondition for test.
2. use prefix path for bin directory.
3. fix invalid thread callback function.
=> [Test] remove unnecessary code

tests/capi/unittest_capi_service_offloading.cc
Add test to set model path of ml-service.
=> [TEST] Add test to set model path of ml-service

tests/capi/unittest_capi_service_agent_client.cc, tests/capi/unittest_capi_service_extension.cc, tests/capi/unittest_capi_service_offloading.cc, tests/capi/unittest_capi_service_training_offloading.cc
- Let the test daemon launches per testsuite. Launching it for each testcase is not practical.
=> [test] Let test daemon launches per testsuite not single testcase

meson.build, tests/capi/meson.build
- Let meson parse mlops-agent.pc to get test daemon path.
=> [build] Set test daemon path by parsing mlops-agent.pc

c/src/ml-api-service-training-offloading.c, tests/test_models/config/training_offloading_receiver.conf
Add the time limit for receiving the necessary data from remote sender
=> [ml-service] Add time limit for required data

c/src/ml-api-service-training-offloading.c, java/android/nnstreamer/build.gradle
Code clean, add internal function to check offloading mode and get private data.
=> [CodeClean] util function to check train mode

c/src/ml-api-service-training-offloading.c
=> [Coverity] fix coverity issue

tests/capi/unittest_capi_service_agent_client.cc, tests/capi/unittest_util.c, tests/capi/unittest_util.h
Add unittest util to get available port
=> [TEST] Add unittest util to get available port

packaging/machine-learning-api.spec
Disable features for mv project release.
=> [Spec] features for mv project

c/src/ml-api-service-private.h, tests/capi/unittest_capi_service_extension.cc, tests/capi/unittest_capi_service_offloading.cc, tests/capi/unittest_capi_service_training_offloading.cc, tests/capi/unittest_util.c, tests/capi/unittest_util.h, tests/test_models/config/service_offloading_receiver.conf, tests/test_models/config/service_offloading_sender.conf, tests/test_models/config/training_offloading_receiver.conf, tests/test_models/config/training_offloading_sender.conf
Add code to set available port number when running offload test.
=> [Test] use available port number

c/src/ml-api-service-offloading.c, c/src/ml-api-service-offloading.h, c/src/ml-api-service-training-offloading.c, tests/capi/unittest_capi_service_offloading.cc
Add util function to request offloading service - send raw data.
=> [Service] util function to request raw data

packaging/machine-learning-api.spec
Update spec file to disable tensorflow-lite ver1.x.
=> [Spec] disable tensorflow-lite ver1.x

c/src/ml-api-service-training-offloading.c
- Remove ready-to-complete property setting
- property is removed
=> [ml-service] Remove ready-to-complete property setting

.github/workflows/_typos.toml, .github/workflows/spell-checker.yml, c/src/ml-api-common.c, c/src/ml-api-inference-single.c, c/src/ml-api-inference-tizen-privilege-check.c, c/src/ml-api-service-offloading.c, c/src/ml-api-service-training-offloading.c, java/android/nnstreamer/src/main/jni/Android-nnfw.mk, java/android/nnstreamer/src/main/jni/Android-snpe.mk, java/build-nnstreamer-android.sh, packaging/machine-learning-api.spec, tests/capi/unittest_capi_inference.cc, tests/capi/unittest_capi_inference_latency.cc, tests/capi/unittest_capi_inference_nnfw_runtime.cc, tests/test_models/config/service_offloading_sender.conf, tests/test_models/config/training_offloading_sender.conf
Add spell checker github action
=> [Actions] Add spell checker

c/src/ml-api-service-agent-client.c
- Let parsing app_info (resolving rpk path) be done in the mlops-agent, not here in ml apis
REF: https://github.com/nnstreamer/deviceMLOps.MLAgent/pull/46
=> [service] Do not parse app_info in service api

.github/workflows/gbs_build.yml
- mlops-agent is irrelevant to ml-api. Remove it.
=> [workflow] Remove unnecessary gbs build

.github/workflows/update_gbs_cache.yml
- Add a workflow to update gbs build cache daily
=> [workflow] Cache gbs build daily

c/src/ml-api-service-offloading.c, c/src/ml-api-service-training-offloading.c, java/build-nnstreamer-android.sh
Code clean, fix mem leak case when parsing json from string.
=>  [CodeClean] leak case when parsing json str

c/include/ml-api-common.h, c/src/ml-api-inference-single.c
Tensor-RT is being prepared in Tizen.
=> enable tensor-rt with C-API

c/src/ml-api-service-offloading.c
Remove AITT connection since AITT has been deprecated.
=> [Edge] Remove AITT support

c/src/ml-api-common.c, c/src/ml-api-internal.h, c/src/ml-api-service-agent-client.c, tests/capi/unittest_capi_service_agent_client.cc
Refactor functions for info-list, use linked list and add new function to append info.
=> [Common] refactor info list

java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c
This patch adds init_filter function of llama2c in android.
See also #563
=> [android] add init filter of llama2c

c/meson.build, c/src/ml-api-inference-pipeline-internal.h, c/src/ml-api-inference-tizen-privilege-check.c, c/src/ml-api-internal.h, packaging/machine-learning-api.spec
From Tizen 9.0, the package for resource mgr is changed and mm-res-mgr is obsolete.
=> [Tizen/C-Api] update res-mgr changes

java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c, meson.build
Code clean, check supported args and set warning flags.
=> [Meson] warning flags

c/src/ml-api-service-training-offloading.c
Code clean, fix mem leak case.
=> [C-Api] fix mem leak case

tests/capi/unittest_capi_service_extension.cc
Increase wait time for processing image classificiion.
=> [TEST] Fix gbs test failure on arm arch.

.github/actions/gitpush/action.yml
Get git diff size by cli tool.
=> [Action] Get git diff size by cli tool

java/android/nnstreamer/src/main/jni/Android-llamacpp-prebuilt.mk, java/android/nnstreamer/src/main/jni/Android-llamacpp.mk, java/android/nnstreamer/src/main/jni/Android.mk, java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c
This patch adds mk files for ndk-build of llama.cpp.
Related with : https://github.com/nnstreamer/nnstreamer-android-resource/pull/45, https://github.com/nnstreamer/nnstreamer/pull/4664
=> [llamacpp] Add .mk files for ndk-build support of llama.cpp

java/build-nnstreamer-android.sh
Update version of ONE runtime for Android build.
=> [Build/Android] version for ONE

java/build-nnstreamer-android.sh
Trivial, fix typo to set android library type.
=> [CodeClean] build type on android

.github/actions/android-build/action.yml, java/build-nnstreamer-android.sh
Change default option to include ONE runtime on android build.
=> [Build/Android] option to build ONE

java/android/nnstreamer/src/main/jni/nnstreamer-android.h
Add missing declaration to initialize native on android.
=> [Android] add extern-c

.github/actions/android-build/action.yml, java/android/nnstreamer/build.gradle, java/android/nnstreamer/src/main/jni/Android-nnstreamer.mk, java/android/nnstreamer/src/main/jni/Android.mk, java/build-nnstreamer-android.sh
Add new option to build native code for ml-service and mlops-agent.
=> [Build/Android] option for ml-service

.github/actions/android-build/action.yml, java/android/nnstreamer/src/main/jni/Android-llamacpp-prebuilt.mk, java/android/nnstreamer/src/main/jni/Android-llamacpp.mk, java/android/nnstreamer/src/main/jni/Android-nnstreamer-prebuilt.mk, java/build-nnstreamer-android.sh
- Add build option for llamacpp.
=> [Android] Add build option for llamacpp

.github/actions/android-build/action.yml, c/src/meson.build, c/src/ml-api-service-offloading.h, c/src/ml-api-service-private.h, c/src/ml-api-service-query.c, c/src/ml-api-service-query.h, c/src/ml-api-service.c, java/android/nnstreamer/src/main/jni/Android-nnstreamer.mk, java/android/nnstreamer/src/main/jni/Android.mk, java/build-nnstreamer-android.sh, java/build-nnstreamer-ubuntu.sh, meson.build, tests/capi/meson.build
Revise features of ml-service.
- query is available with nnstreamer-edge.
- offloading is available with nnstreamer-edge and curl.
=> [C-Api] feature on ml-service

c/src/ml-api-inference-pipeline.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-singleshot.c
Code clean, fix mem leak case when creating new data handle without raw data.
=> [CodeClean] fix leak case

java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-common.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-internal.h
1. Call finalize function when unloading native library.
2. Define macro for jni version.
=> [Android] add unload function

java/android/nnstreamer/src/main/jni/Android-tensorflow-lite.mk, java/build-nnstreamer-android.sh
Update default version of tensorflow-lite on android build.
=> [Android] tf-lite version

java/android/nnstreamer/src/main/jni/Android-nnstreamer-prebuilt.mk, java/android/nnstreamer/src/main/jni/Android-qnn-prebuilt.mk, java/android/nnstreamer/src/main/jni/Android-qnn.mk, java/android/nnstreamer/src/main/jni/Android-tensorflow-lite-prebuilt.mk, java/android/nnstreamer/src/main/jni/Android-tensorflow-lite.mk, java/build-nnstreamer-android.sh
Code clean, update script for qnn prebuild libraries.
=> [Android/Build] cleanup qnn option

.github/actions/android-build/action.yml
Upgrade gstreaemr android ersion with cusrrent stable version.
=> [Android] Upgrade gstreamer android version

c/src/ml-api-inference-internal.c, c/src/ml-api-inference-internal.h, c/src/ml-api-inference-pipeline.c, tests/capi/unittest_capi_inference.cc
Fix invalid return of tensor-if callback function in ml-pipeline.
=> [C-Api] invalid return of tensor-if callback

c/include/ml-api-common.h, c/src/ml-api-inference-single.c
Add these:
- `ML_NNFW_TYPE_LLAMACPP` for llama.cpp
- `ML_NNFW_TYPE_TIZEN_HAL` for tizen ml hal backends
=> [ACR] Add new enums for ML_NNFW_TYPE

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java, java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java, java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/SingleShot.java
Code clean, add new util to read test data file and fix warning.
=> [Android/Test] util to read test data

java/android/nnstreamer/src/main/jni/nnstreamer-native-common.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-internal.h, java/build-nnstreamer-android.sh
It is hard to fix error with old version of gstreamer and build tool.
Set min version of gstreamer 1.24 and ndk r25c to build native library.
=> [Android] gst version

java/android/nnstreamer/src/main/jni/nnstreamer-native-common.c
Add internal function to register/unregister nnstreamer subplugins.
=> [Android] function for plugins

java/build-nnstreamer-android.sh
Upgrade llama.cpp version for android library.
=> [Android] upgrade llama.cpp

.github/workflows/nns_api_testhub.yml
Upload coverage result to TestHub.
=> [Action] Add testhub action

.github/workflows/daily-build-gbs.yml, .github/workflows/gbs_build.yml, .github/workflows/pdebuild.yml
Code clean, set python version for build checker.
=> [Build] python in git action

c/src/ml-api-common.c, c/src/ml-api-inference-pipeline.c, c/src/ml-api-inference-single.c, c/src/ml-api-internal.h, c/src/ml-api-service-agent-client.c, c/src/ml-api-service.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-common.c
Add internal function to replace app data path for android.
=> [Android] replace app data path

java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c, java/android/nnstreamer/src/main/jni/nnstreamer-native-internal.h
Code clean, update structure and function name for tensor info and data class.
=> [Android/CodeClean] name of class info

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestMLInformation.java, java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/MLInformation.java, java/android/nnstreamer/src/main/jni/nnstreamer-native-internal.h
Add new class to handle ml-information.
Later work:
This class will be used from the methods to manage ml models or resources.
=> [Android] new class for ml-information

c/include/nnstreamer-tizen-internal.h, c/src/ml-api-inference-single.c, c/src/ml-api-service-extension.c, tests/capi/unittest_capi_service_extension.cc, tests/test_models/config/config_single_llamacpp_async.conf
Add new callback and options to get the inference result asynchronously.
=> [C-Api] async invoke feature

debian/changelog, java/android/nnstreamer/src/main/jni/Android.mk, meson.build, packaging/machine-learning-api.spec
Update version info for Tizen 10.0 M2 release.
=> [Release] update version for Tizen release
