packaging/machine-learning-api.spec

'Provides' field in spec file causes unresolvable problems since our
customers use pkg-config files like 'BuildRequires: pkgconfig(capi-nnstreamer)'.
This patch removes 'Provides' field so that this package successfully
builds on the OBS server.

[Spec] Remove 'Provides' field in spec file @open sesame 02/17 08:20

---

packaging/machine-learning-api.spec

Some necessary packages such as nnstreamer-tizen-sensor are omitted from
Tizen platform image. This patch adds the 'Requires' section to
capi-machine-learning-inference package to operate properly.
* Related Issue: https://code.sec.samsung.net/jira/browse/TSDF-247
3. Tizen UTC is passed.

[spec] Add Requires section for Tizen platform image @open sesame 02/26 14:35

---

c/include/nnstreamer-capi-private.h
c/src/nnstreamer-capi-single.c
c/src/nnstreamer-capi-util.c

In single-shot timeout case, the flag to release output handle may reset when setting short timeout value.
To prevent this case, add output handle to del-list and change params to set input/output handle in invoke thread.

[C-Api] fix res leak in timeout mode

---

tests/capi/meson.build

- Default timeout value for meson test is 30 secs
- Set timeout value of 100 secs for unittests
Before:
```
$ ninja test                                                                                                   
[0/1] Running all tests.                                                                                       
1/2 unittest_capi_inference                 OK      16.85 s                                                    
2/2 unittest_capi_inference_latency         TIMEOUT 30.00 s                                                    
Ok:                    1                                                                                       
Expected Fail:         0 …
```

[test] Set timeout for meson test

---

tests/capi/unittest_capi_inference.cc

Ignore tensor name comparison in tf-lite testcase.
NNStreamer tf-lite plugin will set tensor name.

[Test] tensor name in tf-lite tc

---

c/include/nnstreamer-capi-private.h
c/src/nnstreamer-capi-pipeline.c
tests/capi/unittest_capi_inference.cc

When developer constructs a pipeline with custom filter or if-condition, add ref count to custom handle.
Prevent custom handle unregistration if pipeline is running.

[C-Api] add ref-count to custom filter/if handle

---

c/src/nnstreamer-capi-util.c

This patch enables singleshot inference from `ML_NNFW_TYPE_NNTR_INF`
I read code throughly to look where to change but it was only one line,
Please review if there are more things to be done.

[Singleshot] Support nntrainer inference

---

c/src/nnstreamer-capi-pipeline.c

Since the length of the pipeline string is too long, the error message cannot be checked.
For easier debugging, this log message should be divided.
Signed-off-by: Hyoung Joo Ahn <hello.ahn@samsung.com>

[Log] divide a log message

---

packaging/run_unittests.sh

In main routine, return cannot be used.
Return values by calling exit instead.

Fix unit test script

---

packaging/machine-learning-api.spec

This patch uses tar archiving instead of tar.gz instead of VD QBuild
system.

[Spec] Use tar archiving instead of tar.gz

---

c/include/nnstreamer-capi-private.h
c/src/nnstreamer-capi-single.c
c/src/nnstreamer-capi-tizen-privilege-check.c
meson.build
meson_options.txt
packaging/machine-learning-api.spec

This requires
https://review.tizen.org/gerrit/#/c/platform/core/multimedia/libmm-camcorder/+/255956/ (updated)
to be merged and deployed. Or maintainers may do group-SR.
Fixes https://github.com/nnstreamer/nnstreamer/issues/1734

[Tizen/Privilege] Use newly exported MMFW headers @open sesame 4/5 18:56

---

packaging/machine-learning-api.spec

To support the backward compatibility of Tizen 6.0,
libcapi-nnstreamer.so is moved to capi-machine-learning-inference
package.

[Spec] Move libcapi-nnstreamer.so to capi-machine-learning-inference package

---

java/android/nnstreamer/src/main/jni/nnstreamer-native-pipeline.c

We cannot guarantee the data object from java is available while running the pipeline.
Set clone when pushing data to src element.

[Android/Pipeline] clone data from src element

---

c/include/nnstreamer.h
c/src/nnstreamer-capi-pipeline.c
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/Pipeline.java
java/android/nnstreamer/src/main/jni/nnstreamer-native-pipeline.c
tests/capi/unittest_capi_inference.cc

Add new API to flush the pipeline.
If new input should be run without old data in pipeline, this is necessary to clear all.

[C-Api] new API to flush the pipeline @open sesame 4/29 11:23

---

c/src/nnstreamer-capi-pipeline.c

- Some gstreamer elements fail to send `gst_event_new_flush_start`
- Spilt `_flush_start` and `_flush_stop` to call `_flush_stop`

[C-API] Fix Pipekline Flush API

---

java/android/build-nnstreamer-android-lib.sh
java/android/gstreamer_android-1.0.c.in.patch

- Add Android GStreamer build option for tracing in build script
- Add patch for file `gstreamer_android-1.0.c.in` to enable this feature
REF: https://gstreamer.freedesktop.org/documentation/additional/design/tracing.html?gi-language=c
With option `--enable_tracing=yes`, latency of each element is logged (in nanoseconds)
example log:
```
I/GStreamer+GST_TRACER: 0:00:04.955265623 0x7d103654a0 :0: element-latency, element-id=(string)0x7d701e81b0, element=(string)tensoraggregator1, src=(string)src, time=(guint64)27917, ts=(guint64)4955157082;
I/GStreamer+GST_TRACER: 0:00:04.955327707 0x7d10365630 :0: element-latency, element-id=(string)0x7da0258030, element=(string)queue0, src=(string)src, time=(guint64)182607135, ts=(guint64)4955210571; …
```

[Android] Build GStreamer with tracing 

---

packaging/machine-learning-api.spec

Since rpmbuild explicitly exclude the name from the library rpm,
libcapi-nnstreamer.so is not provided as below.
```bash
$ rpm -qp --provides capi-machine-learning-inference-1.7.2-0.armv7l.rpm
capi-machine-learning-inference = 1.7.2-0
capi-machine-learning-inference(armv7l-32) = 1.7.2-0
libcapi-nnstreamer.so.1
```
This patch adds the provides section to capi-machine-learning-inference
package so that capi-machine-learning-inference provides
libcapi-nnstreamer.so.

[Spec] Add the provides section to capi-machine-learning-inference package @open sesame 5/06 19:40

---

packaging/machine-learning-api.spec

If architecture is aarch64 or x86_64, the 64bit option should be added.
If not, the wrong so file is provided as below.
$ rpm -qp --provides capi-machine-learning-inference-1.7.2-0.aarch64.rpm
capi-machine-learning-inference = 1.7.2-0
capi-machine-learning-inference(aarch-64) = 1.7.2-0
libcapi-nnstreamer.so
libcapi-nnstreamer.so.1()(64bit)

[Spec] Add the Provides option in case of 64bit

---

c/include/nnstreamer.h
c/src/nnstreamer-capi-pipeline.c

Refer: https://github.com/nnstreamer/nnstreamer/issues/2581
This provides API signature and code skeleton for
callback support of app-src elements in ML-API pipelines.
CC: @junmin-kim

[API/Skeleton] App Src Callback support

---

c/capi-ml-common.pc.in
c/capi-ml-inference.pc.in
c/meson.build

- [CAPI/ml-common] Add require to base-common
```
When a developer tries to add dependency to `capi-ml-common` they have
to care about adding dependency to `capi-base-common` as well because
`capi-ml-common` is actually depending upon `capi-base-common`
This patch resolves the issue by adding require to `capi-base-common`
in the pc file.
resolves #57
```
resolves #57

[CAPI/ml-common] Add require to base-common

---

java/android/nnstreamer/src/main/jni/Android-flatbuf.mk

Change version check of the flatc from error to warning.
Even if the flatbuffers compiler has different versions, compatibility can be maintained.
Tested with
- System flatc version: 2.0.0
- Android flatc version: 1.12.0
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
2. Run test: [ ]Passed [ ]Failed [* ]Skipped

[Flatbuf] Change version check of the flatc @open sesame 06/09 17:21

---

c/include/nnstreamer-capi-private.h
c/src/nnstreamer-capi-pipeline.c
c/src/nnstreamer-capi-util.c

Fixes #nnstreamer/2600
Note that locally created-and-freed ml-tensors-data
are not required to be protected.

Thread safety for ml_tensors_data APIs @open sesame 5/27 17:10

---

c/src/nnstreamer-capi-pipeline.c

This patch fixes the coverity issue: "waiting while holding a lock".
Before entering the loop, the mutex lock is released so that other thread can
use the CPU.

[C-API] Fix the coverity issue

---

c/include/nnstreamer-capi-private.h
c/src/nnstreamer-capi-pipeline.c
c/src/nnstreamer-capi-util.c

This patch fixes the case of Time of Check Time of Use bug in
ml_pipeline_custom_easy_filter_register().
The provided arguments `in` and `out` are first checked for validity
under their locks and then used for clone again under their locks.
However, between the two operations, both the variable are left lock
free, and the two variables can become invalid.
This patch adds the corresponding fix by adding support for
checking validity of ml_tensors_info_s lockfree which is done
under the lock acquired inside ml_tensors_info_clone().
Further, as a minor fix, redundant locking and unlocking
has been removed from ml_pipeline_custom_easy_filter_register().
See also #42 https://github.com/nnstreamer/api/pull/42#issuecomment-840265534
Resolves https://github.com/nnstreamer/nnstreamer/issues/2600 …

[capi] Update on thread safety for ml_tensors_info

---

java/android/nnstreamer/build.gradle

For android release, set minimum sdk version to 24.

[Android] min sdk version to 24

---

c/include/nnstreamer-capi-private.h
c/src/nnstreamer-capi-pipeline.c
tests/capi/unittest_capi_inference.cc

In flexible tensor stream, sink and src handle cannot set exact tensor info from pad caps.
To handle flex-tensor, ignore tensor info while configuring the element handle.

[C-Api] handle flexible tensor

---

c/src/nnstreamer-capi-util.c

To support VD product, this patch adds the ML_NNFW_HW_NPU_SLSI case
to ml_nnfw_to_accl_hw() function.

[C-Api/Util] Add ML_NNFW_HW_NPU_SLSI case to converting function @open sesame 07/01 09:28

---

java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c

We should call subplugin registration only on Android.
Remove unnecessary feature in native code.

[JNI] remove unnecessary feature in native

---

tests/capi/unittest_capi_inference.cc

- Add tensor clone test
ml_tensor_info_clone function changed to check the number of the
tensors of source info.
So, set the num_tesnors for source info.

[TEST] Add tensor clone test

---

c/src/nnstreamer-capi-util.c

When checking fw with model files is failed, it returns null and this will print warning message even if this works properly.
Update macro to not print this message. (requested from VD)

[C-Api] remove warning while checking framework

---

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java

With https://github.com/nnstreamer/nnstreamer/pull/3433,
- SNAP v3.0 supports tensorflow lite model.
- Add pipeline and singleshot test using it (image classification with mobilenet)

[Android] Test SNAP with tensorflow lite model

---

c/include/nnstreamer.h
c/src/nnstreamer-capi-single.c
c/src/nnstreamer-capi-util.c

The patch updates the name 'srnpu' to 'trixengine'.

[C-API] Rename srnpu to trixengine

---

c/include/nnstreamer.h
c/src/nnstreamer-capi-single.c
c/src/nnstreamer-capi-util.c

According to the Tizen naming convention, the names of the entities must
be composed of upper case letters. This patch fixes this issue.

[C-API] Use ML_NNFW_TYPE_TRIX_ENGINE instead of ML_NNFW_TYPE_TRIx_ENGINE

---

c/include/nnstreamer.h
c/src/nnstreamer-capi-pipeline.c
tests/capi/unittest_capi_inference.cc

Change src-callback function name.
- Names of callback function types should have the '_cb' suffix.
- A module providing callbacks called on events should support exactly one of two registration schemes.
> single callback registration: {module}_set_{details}_cb

[C-API] Change src-callback name @open sesame 8/18 09:57

---

packaging/machine-learning-api.spec
tests/capi/meson.build
tests/capi/unittest_capi_datatype_consistency.cc

There are type re-definitions in C ML-API, which
should inherit values from nnstreamer and gstreamer.
Add unittests that ensure consistency.
Fixes https://github.com/nnstreamer/nnstreamer/issues/2587
CC: @kparichay 

Unittest: data type consistency with nnstreamer/gstreamer @open sesame 8/13 11:56 

---

c/src/nnstreamer-capi-single.c
debian/changelog
java/android/nnstreamer/src/main/jni/Android.mk
meson.build
packaging/machine-learning-api.spec

Don't close single handle during invoke process.
If single handle is released during invoke prcoess, an interpreter may
access invalid memory.

[Single] Don't close single handle during invoke process

---

c/src/ml-api-inference-single.c

<details><summary>[Singleshot] Enhance dim inference for nntrainer</summary><br />
There was a voc that `ml_single_open(&single, 'model.ini', NULL, NULL,
ML_NNFW_TYPE_NNTR_INF, ML_NNFW_HW_ANY);` should work.
This was not feasible because the nntrainer inference filter is not
defining `getInputDim()`, `getOutputDim()` on purpose to make it able to
infer output dimension from input dimension in pipeline scenario.
This patch introduce the dimension inferencing mechanism for nntrainer
to make it coherent with the pipeline api.
Below rules apply when input_info or output_info is nullptr for
nntrainer.
1. After opening the framework, allow calling set_input_dim with input_info with
count==0 in case of nntrainer.
2. nntrainer checks if input_info->count==0, if true, nntrainer assums
it should be …

[Singleshot] Enhance dim inference for nntrainer

---

packaging/machine-learning-api.spec

This patch fixes the typo in Requires section.
* capi-machine-larning-common -> capi-machine-**learning**-common

[Spec] Fix the typo in Requires section

---

c/include/ml-api-common.h
c/include/nnstreamer.h
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java

Code clean, it is recommended to not use stddef for NDK build, use stdlib instead.

[Build/CodeClean] std headers

---

c/include/ml-api-common.h
c/src/ml-api-common.c
c/src/ml-api-internal.h

commit a4d4b6570bcb2c451f8f4ff83bd2c63fd9289ec6 (HEAD -> capi/err5, fork/capi/err5, capi/err4)
Author: MyungJoo Ham <myungjoo.ham@samsung.com>
Date:   Tue Oct 26 13:47:19 2021 +0900
C-API/Common: a few usage examples of error repoting infra.
A few usage examples of error reporting infra added.
More functions will be using this soon.
Unit test cases will follow later.
commit c549bb01c0b0db17071acd5f8d36a63b12669c34
Author: MyungJoo Ham <myungjoo.ham@samsung.com>
Date:   Tue Oct 26 13:46:41 2021 +0900
C-API/Common: macro for formatting error messages.
New macros for error reporting infrastructure with some more info.

C-API/Common: a few usage examples of error repoting infra.

---

c/meson.build

Because of the bug in the meson file, Requires section in
capi-ml-inference.pc is empty. It causes the compile-time error when
using ML APIs. This patch fixes this bug.
```bash
$ cat ./usr/lib/pkgconfig/capi-ml-inference.pc
...
Name: tizen-api-ml-inference
Description: ML inference API for Tizen
Version: 1.8.0
Requires: 
Libs: -L${libdir} -lcapi-nnstreamer
...
```
```bash
$ cat ./usr/lib/pkgconfig/capi-ml-inference.pc
...
Name: tizen-api-ml-inference
Description: ML inference API for Tizen
Version: 1.8.0
Requires: capi-ml-common
Libs: -L${libdir} -lcapi-nnstreamer
...
```

[C-Api] Fix the omitted Requires section in capi-ml-inference.pc

---

java/android/nnstreamer/src/main/jni/Android-nnfw.mk
java/android/nnstreamer/src/main/jni/Android-nnstreamer-prebuilt.mk
java/android/nnstreamer/src/main/jni/Android-pytorch.mk
java/android/nnstreamer/src/main/jni/Android-snpe.mk

- Add a comment for native developers.
- Exclude xnnpack and other prebuilt libs from `LOCAL_WHOLE_STATIC_LIBRARIES`
to avoid link crash issue with tflite which also contains xnnpack and other common prebuilt libs
-  Add comments for nnfw and snpe makefiles about external libs

[build/android] Fix Pytorch makefile to compatibile with tflite (xnnpack) @open sesame 12/08 16:52

---

c/meson.build
c/src/ml-api-internal.h
tests/capi/meson.build
tests/capi/unittest_util.c

With unittesting, especially in GBS, dlog output is
not shown because dlog server is not running.
Replace it with stderr print in unittesting
for better readability in GBS.
This is similar with
https://github.com/nnstreamer/nnstreamer/pull/3571

C/common: override dlog infra with stderr for unit testing

---

.github/CODEOWNERS

Currently, the source code path of the CODEOWNER is set differently than we were intended.
For example, /c/* mathces files like `c/README.md`
but not further nested files like `c/src/ml-api-common.c`
To include nested files, fix source code path syntex.
refer: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file

[CODEOWNER] Fix source code path syntex.

---

tests/capi/unittest_capi_inference.cc

Both plugin_availability_fail_invalid_01_n and
plugin_availability_fail_invalid_02_n have the same test code. This
patch updates the parameter to test other case.

[TEST] Update the test case

---

c/src/ml-api-inference-single.c

When the framework version does not match the given
model's requirement, STREAM_PIPE error may happen.
Because it appears that such cases are common,
add more explanation.
Related with https://github.com/nnstreamer/nnstreamer/issues/3603

C/single: elaborate invoke stream-pipe error.

---

.github/CODEOWNERS

The last matching pattern takes the most precedence.
Change orders.
Refer: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

[CODEOWNERS] Fix codeowners

---

java/android/nnstreamer/src/main/jni/Android-pytorch.mk
java/build-nnstreamer-android.sh

- Support pytorch v1.10.1 for android (only arm64)
- Set v1.10.1 as default version

[android/pytorch] Add pytorch v1.10.1 android support

---

c/src/ml-api-inference-internal.c

The name 'restricted-elements' of nnstreamer configuration is not
matched as its real operation. Because of this reason, its name is
renamed to 'allowed_elements'. This patch updates the related code.
* https://github.com/nnstreamer/nnstreamer/pull/3635

[C/inference] Use allowed_elements instead of restricted-elements @open sesame 01/10 16:30

---

tests/capi/unittest_capi_inference.cc
tests/capi/unittest_capi_inference_latency.cc
tests/capi/unittest_capi_inference_nnfw_runtime.cc

1. init gstreamer before starting the unittest.
2. check element restriction flag from config file.

[C-Api/Test] condition to check allowed element @open sesame 01/25 17:47

---

c/meson.build
meson.build

<details><summary>Fix libcapi-nnstremer is empty due to linker optimization</summary><br />
From #131, libcapi-nnstreamer.so became empty because
libcapi-nnstreamer.so does not use any symbol from
libcapi-nnstreamer-single, libcapi-nnstreamer-pipeline.so
This should be semantically resolvable by using 'link-whole' argument in
meson but it is not implemented for shared_library.
This patch address the issue by disabling `-bas-needed=false` in meson
and add -Wl,--as-needed to global linker argument.
See also: https://github.com/mesonbuild/meson/issues/3046.
</details>

Fix libcapi-nnstremer is empty due to linker optimization

---

c/capi-ml-inference.pc.in
c/meson.build
debian/ml-inference-api-dev.install

<details><summary>[Debian] update ml-inference-api-dev package</summary><br />
After #131, ml-inference-api-dev is relying on capi-ml-inference-single
and capi-ml-inference-pipeline pc.
It might have been better that ml-inference-api-dev relying on
ml-inference-single/pipeline-dev. As the package is not introduced,
this patch add pc files into the ml-inference-api-dev package.
See also: https://github.com/nnstreamer/nntrainer/issues/1853#issuecomment-1064220362
</details>

[Debian] update ml-inference-api-dev package

---

meson.build

<details><summary>[meson] change global link -> project link</summary><br />
As recommended from a review in #137, add_global_link_argument has
changed to add_project_link_argument
</details>

[meson] change global link -> project link

---

packaging/machine-learning-api.spec

To maintain backward compatibility, capi-machine-learning-inference
package should require pipeline, single and common libraries. However,
common is omitted and it can cause break issues when making platform
image. This patch fixes this bug.
```bash
$ rpm -q --requires capi-machine-learning-inference-1.8.0-0.armv7l.rpm
...
capi-machine-learning-inference-pipeline = 1.8.0-0
capi-machine-learning-inference-single = 1.8.0-0
libcapi-nnstreamer.so.1
...
```
```bash
$ rpm -q --requires capi-machine-learning-inference-1.8.0-0.armv7l.rpm
...
capi-machine-learning-common = 1.8.0-0
capi-machine-learning-inference-pipeline = 1.8.0-0 …
```

[Package] Bugfix for package dependency

---

packaging/machine-learning-api.spec

After modifying C-API packages, the SMACK label was omitted for
each package. And library packages contain unnecessary so file.
This patch adds omitted SMACK label and cleans up the contents of
the package.
```bash
$ rpm -qlp capi-machine-learning-common-1.8.0-0.x86_64.rpm
/usr/lib64/libcapi-ml-common.so
/usr/lib64/libcapi-ml-common.so.1
/usr/lib64/libcapi-ml-common.so.1.8.0
$ rpm -qlp capi-machine-learning-common-devel-1.8.0-0.x86_64.rpm
/usr/include/nnstreamer/ml-api-common.h
/usr/lib64/pkgconfig/capi-ml-common.pc
```
```bash
$ rpm -qlp capi-machine-learning-common-1.8.0-0.x86_64.rpm
/usr/lib64/libcapi-ml-common.so.1 …
```

[Package] Add SMACK label and cleanup the package

---

c/src/ml-api-service-db.cc
packaging/machine-learning-api.spec

Because of SMACK control, the application process cannot access the
'/opt/usr/dbspace'. To meet the Tizen M1 release schedule, this patch
uses '/tmp' as database space. It is just a workaround and will be fixed
in the right way.

[C-API/Service] Workaround for dbspace failure

---

c/src/ml-api-inference-single.c

This patch allows tvn model when using VD_AIFW framework.
Signed-off-by: yelini-jeong <yelini.jeong@samsung.com>

[single] Allow tvn model when using VD_AIFW

---

c/src/ml-api-common-tizen-feature-check.c
c/src/ml-api-internal.h
tests/capi/unittest_capi_datatype_consistency.cc
tests/capi/unittest_capi_inference.cc
tests/capi/unittest_capi_inference_latency.cc
tests/capi/unittest_capi_inference_nnfw_runtime.cc
tests/capi/unittest_capi_inference_single.cc
tests/capi/unittest_capi_service.cc

Each Tizen ML feature state (inference, training, service) should be managed separately.

[C-Api] handle each feature state

---

c/doc/nnstreamer_doc.h

This patch removes the unnecessary doxygen tag in doc.h file.

[C-API] Remove unnecessary doxygen tag

---

c/include/ml-api-common.h
c/src/ml-api-internal.h

ml_strerror(), ml_error() functions are not ready to release. So they
are moved to internal header.

[C-API] Move ml_strerror() to internal header

---

c/include/ml-api-common.h
c/src/ml-api-internal.h

Since ml_strerror() & ml_error() functions are used in webapi-plugins
module, they should be in ml-api-common.h header.

[C-API] Revert "Move ml_strerror() to internal header"

---

c/src/ml-api-inference-pipeline.c
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
packaging/machine-learning-api.spec
tests/capi/unittest_capi_inference.cc

- If current caps is given, use it rather than allowed caps.
- Use caps "image/png" when the pipeline is "appsrc caps=image/png ! pngdec ! ... "
- Add a test for decoding pngfile using appsrc (C API and android JAVA)
- It check the equality of decoded orange.png using simple pipline
with raw file (orange.raw)
This resolves https://github.com/nnstreamer/nnstreamer/issues/3753

[pipeline API] Let pipeline src use current caps when it's given

---

c/include/ml-api-common.h

This patch fixes the typo in ml-api-common.h file.

[C-API] Fix the typo

---

c/include/ml-api-common.h
c/include/nnstreamer-single.h
c/include/nnstreamer-tizen-internal.h
c/src/ml-api-common.c
c/src/ml-api-inference-single.c
c/src/ml-api-internal.h
tests/capi/unittest_capi_inference_single.cc

- Add four new APIs:
ml_option_create
ml_option_destroy
ml_option_set
ml_single_open_with_option
- It uses GHashTable {const char* key : void* value} to store various options for ml_single_open
- Add some testcases using newly added ml_option APIs

[C-API/Single] Add new API for "ml_option"

---

java/android/nnstreamer/src/main/jni/Android-tensorflow-lite.mk
java/build-nnstreamer-android.sh

- Add tflite v2.8.1 support and set it as default
- This PR requires https://github.com/nnstreamer/nnstreamer-android-resource/pull/32 to be merged

[android] Set tensorflow-lite v2.8.1 as default

---

daemon/gdbus-util.c
daemon/includes/gdbus-util.h
daemon/includes/test-dbus-interface.h
daemon/main.c
daemon/meson.build
daemon/test-dbus-impl.c
dbus/test-dbus.xml
packaging/machine-learning-api.spec
tests/daemon/meson.build
tests/daemon/unittest_ml_agent.cc
tests/meson.build
tests/services/meson.build
tests/services/org.tizen.machinelearning.service.service.in

To test the ML Agent daemon process itself, this PR adds the unit tests and implementation for the Test DBus interface. To run unit tests in the GBS environment, the session type of the DBus bus is necessary. So It adds the command-line option to support the session bus. The default option is `SYSTEM` so it is just unit test purpose.
```bash
$ ./machine-learning-agent --help
Usage:
machine-learning-agent [OPTION?]
Help Options:
-h, --help        Show help options
Application Options:
-v, --verbose     Be verbose
-s, --session     Bus type is session
```
```bash
[   73s] ./tests/capi/unittest_ml_agent
[   73s] [==========] Running 1 test from 1 test suite.
[   73s] [----------] Global test environment set-up.
[   73s] [----------] 1 test from MLAgentTest
[   73s] [ RUN      ] …
```

[TDD] Add unit tests for ML Agent and implementation

---

c/include/ml-api-common.h
c/src/ml-api-common.c
c/src/ml-api-inference-internal.c

Declare API formats for API change review process.
Note:
Fp16 is generally supported by arm/arm64 compilers.
However, x64/x86 compilers usually don't support it
(GCC>=12 is required along with some compiler flags).

[C-API/common] Add fp16 type.

---

daemon/includes/dbus-interface.h
daemon/includes/gdbus-util.h
daemon/includes/modules.h
daemon/includes/service-db.hh
daemon/meson.build
daemon/model-dbus-impl.cc
daemon/service-db.cc
dbus/model-dbus.xml
packaging/machine-learning-api.spec
tests/daemon/meson.build
tests/daemon/unittest_dbus_model.cc

This patch newly adds the unit test case of the DBus Model interface and its implementation code. DBus Model interface handles the neural network model files by storing the name of a model file and its file path in the internal key-value database. To improve the maintainability, this PR defines the `IMLServiceDB` interface so the backend database could be changed easily.
* Use `#define` header-guard instead of `#pragma once` since it is not standard in C++
* Move the `client proxy` to SetUp() method.
* Remove unused headers
* Fix the boilerplate code
* First draft
* Implementation of DBus Model interface and its test cases

[TDD] Implementation of DBus Model interface @open sesame 08/03 11:50

---

dbus/machine-learning-agent.service.in

To comply with the Tizen security rule, this patch updates the systemd
service file.
- Enable DBus activation
- Set User and Group ID as service_fw
- Set network capabilities

[ML Agent] Update systemd service file

---

daemon/includes/dbus-interface.h
daemon/meson.build
daemon/pipeline-module.cc
dbus/pipeline-dbus.xml

- Change the method name `register_pipeline` -> `launch_pipeline`.
This method launch pipeline with given service name, if the pipeline
description is stored in the DB beforehand.
- Change the module source file into cpp file. It's to use the db implementation.
- Add `set_pipeline`, `get_pipeline`, and `delete_pipeline` dbus call.
- These correspond with `ml_service_[set|get|delete]_pipeline` APIs.

[ml-agent] Add set/get/delete pipeline method to pipeline module

---

daemon/meson.build
packaging/machine-learning-api.spec

This patch enables the PIE (Position Independent Executable) option to
comply with Tizen security. If this option is not enabled, the daemon
file will be lost its executable permission when making platform image.
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped
```bash
INFO: ###### ASLR not applied list ######
INFO: /usr/bin/winpr-hash
INFO: /usr/bin/machine-learning-agent
...
```

[ML Agent] Enable PIE option for Tizen security check

---

c/src/ml-api-service-agent-client.c

- Set System type for ml-service API.
- If fails to get system bus, try with session type (for unittest)

[ml-service] Fix session type of ml-service API @open sesame 08/22 18:35

---

c/include/ml-api-service.h
c/src/ml-api-service-agent-client.c
daemon/includes/dbus-interface.h
daemon/pipeline-module.cc
dbus/pipeline-dbus.xml
tests/capi/unittest_capi_service_agent_client.cc

- Add some document for newly added service APIs.
- Change API names
`ml_service_getstate_pipeline` -> `ml_service_get_pipeline_state`
`ml_service_destroy_pipeline` -> `ml_service_destroy`
- Fix return values and free proxy properly.

[After #196][service] Add document for newly added service APIs @open sesame 08/31 11:35

---

tests/capi/unittest_capi_inference_nnfw_runtime.cc

- Count each sink for multi model pipeline nnfw unittest to prevent occasional CI test failure

[test] Count each sink for multi model pipeline nnfw unittest

---

c/src/ml-api-inference-pipeline.c
daemon/pipeline-module.cc

- Free allocated `dllist` when allocation of other list is failed.
- Initialize an uninitialized value.

[svace][trivial] Fix svace issues for leak and uninitialize

---

c/include/ml-api-service.h

- Add a sentence which warns users to keep their name (key) safe.

[service] Add a guide for the "key" when using ml_service_set_pipeline

---

daemon/main.c

- Add missing header for errno to enable build daemon in ubuntu.

[ml-agent] Add missing header

---

c/meson.build
c/src/ml-api-service-agent-client.c
c/src/ml-api-service-common.c
c/src/ml-api-service-private.h
c/src/ml-api-service-query-client.c
debian/control
packaging/machine-learning-api.spec
tests/capi/unittest_capi_service_agent_client.cc

- Implement two query client APIs: ml_service_query_create and ml_service_query_request
- `ml_service_query_create` creates a query client handle with given ml-option instance. The handle maintains a gstreamer pipeline with description:
"appsrc ! other/tensors,... (caps string given with ml-option) ! tensor_query_client ... (props given with ml-option) ! tensor_sink"
- `ml_service_query_request` takes an input tensor and feed it to the pipeline. An output from tensor_sink is copied to given output handle.
- Implement common feature for server and query client
- Let ml_service_destroy can destroy multiple types of service handle

[service] Add ml service query client

---

c/src/ml-api-service-agent-client.c
c/src/ml-api-service-common.c
tests/capi/unittest_capi_service_agent_client.cc

- Add code for handling invalid parameters in ml_service_destroy and ml_service_get_pipeline_state.
- Add negative TCs for launch and get_state APIs
- Add testcases with explicitly corrupted parameters.

[test][service] Add unittests for service APIs

---

daemon/pipeline-module.cc

- When pipeline is destroyed, agent tried to set its state as GST_STATE_NULL.
- However, pipelines which contain tensor_query_* elements make hanging
when change te state. To resolve this, as a workaround, this commit just unref it.
- After fix this issue in tensor_query / nnstreamer-edge, revive this code.
- Remove lock/unlock when freeing pipeline instances

[agent] Fix occasional hanging issue when destroy certain pipelines

---

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java

- Fix the snpe filter test. The usage of multiple output model was changed.

[android] Fix snpe test of multiple moutput model

---

c/include/meson.build
c/include/platform/meson.build
c/meson.build
c/src/meson.build
daemon/meson.build
dbus/meson.build
meson.build
packaging/machine-learning-api.spec
packaging/run-unittest.sh
tests/capi/meson.build

- Generate gcov and unittest package with "gcov 1" option for tizen test
automation tools.
- Costruct paths automatically using `files` not manually. This patch fixes wrong object file names.
Foe example, 
before: _home_abuild_rpmbuild_BUILD_capi-machine-learning-inference-1.8.3_c_src_ml-api-inference-internal.c.o
after: ml-api-inference-internal.c.o

[Tizen] Generate packages for automation test tools

---

java/android/nnstreamer/build.gradle

- Add missing arg NNSTREAMER_EDGE_ROOT in build.gradle

[build/android] Add missing arg in build.gradle

---

c/src/ml-api-inference-single.c

The output tensor does not contain the tensors-info when invoking the model.
Update in/out tensors-info in single-shot handle.

[Single] set tensors-info in output handle

---

c/src/ml-api-common.c
c/src/ml-api-inference-single.c
c/src/ml-api-internal.h
tests/capi/unittest_capi_inference.cc

Clone input data in single-shot, to prevent use-after-free case when invoking a model with timed out option.
Signed-off-by: Jaeyun Jung <jy1210.jung@samsung.net>

[Single] prevent use-after-free case

---

c/meson.build
c/src/ml-api-inference-tizen-privilege-check.c
c/src/ml-api-internal.h
packaging/machine-learning-api.spec
tests/capi/unittest_capi_inference.cc

From Tizen 7.5, privacy-privilege-mgr API will be deprecated.

[Tizen/PPM] deprecated API from 7.5

---

daemon/includes/service-db.hh
daemon/model-dbus-impl.cc
daemon/pipeline-module.cc
daemon/service-db.cc

Code clean, we will change the database later - level-db to sqlite. Change class name and remove interface to ML-Service DB.

[Service/CodeClean] change class name @open sesame 2/8 10:32

---

c/src/ml-api-inference-single.c

This patch adds the error number for the missing argument of the format specifier.
* Need to apply the Tizen 7.0 branch

[Single] Fix coverity issue

---

daemon/includes/pkg-mgr.h
daemon/main.c
daemon/meson.build
daemon/pkg-mgr.c
meson.build
packaging/machine-learning-api.spec

To get the event from the package manager, the callback function should be registered in ML Agent. This patch adds the skeleton code to get the install, uninstall, and upgrade event of the resource package from the package manager. Related work such as update the database of ML Agent should be needed.
```bash
root:~> /usr/bin/machine-learning-agent 
init gstreamer
type: rpk, package: org.tizen.mlmodel, event_type: 1, event_state: 0
package path: /opt/usr/globalapps/org.tizen.mlmodel/shared/res
- file: mobilenet_v2_1.0_224.tflite
- file: model_description.xml
type: rpk, package: org.tizen.mlmodel, event_type: 1, event_state: 2
type: rpk, package: org.tizen.mlmodel, event_type: 0, event_state: 0
type: rpk, package: org.tizen.mlmodel, …
```

[Service/PkgMgr] Add skeleton code for the package manager

---

daemon/service-db.cc
tests/capi/unittest_capi_service_agent_client.cc

- Check the number of changed rows after the DELETE query
- Add some negative testcases.

[agent][DB] Fix "delete_pipeline" to check the number of changed rows

---

c/src/ml-api-service-agent-client.c
tests/capi/unittest_capi_service_agent_client.cc

Validate model path when registering a model to database. It should be an absolute path and not symbol link file.

[Service] validate model path

---

packaging/machine-learning-api.spec

Fix gcno file path of gcov pacakge for compatibility with the Tizen line coverage automation tool.
- Debug message:
[DEBUG]:[2023-03-13,04:09:31]:[host_cmd.py:cmd:77]:geninfo: Warning: ('gcov') skipping .gcda file /home/ttf/jenkins_workspace/workspace/CEC_TIZEN_75_RPI4_GCOV_COVERAGE/CEC/res/coverage_gcov/gcov_data/capi-machine-learning-inference-1.8.3/build/c/src/libcapi-ml-service.so.1.8.3.p/ml-api-service-query-client.c.gcda because corresponding .gcno file is missing
- Before: capi-machine-learning-inference-1.8.3\c\src\libcapi-ml-service.so.1.8.3.p
- After: capi-machine-learning-inference-1.8.3\ **build** \c\src\libcapi-ml-service.so.1.8.3.p

[Tizen] Fix gcno file path of gcov pacakge.

---

c/src/meson.build
c/src/ml-api-common.c
c/src/ml-api-service-agent-client.c
daemon/includes/dbus-interface.h
daemon/includes/service-db.hh
daemon/model-dbus-impl.cc
daemon/service-db.cc
dbus/model-dbus.xml
meson.build
packaging/machine-learning-api.spec
tests/capi/unittest_capi_service_agent_client.cc

- Add dbus methods to handle model service APIs
- Update/Add service-db methods in sqlite3 backend
- Implement dbus method callbacks
- Implement new APIs ml_service_model_* using gdbus and json-glib

[Service/Model][Daemon] Implement APIs for the ml-service-model and daemon-side methods

---

daemon/model-dbus-impl.cc
tests/capi/unittest_capi_service_agent_client.cc

- Print exception message rather than simple error log
- Add missing `ml_option_destroy` in a unittest

[agent][trivial] Print exception and fix memleak

---

c/src/ml-api-service-agent-client.c
c/src/ml-api-service-common.c
tests/capi/unittest_capi_service_agent_client.cc

- If failed to connect with dbus, return ML_ERROR_IO_ERROR
rather than ML_ERROR_NOT_SUPPORTED, which should be check with tizen
feature.
- Add negative TC with DBUS unconnected.

[service] Change error code not_support into io_error

---

c/src/ml-api-service-common.c
c/src/ml-api-service-private.h
tests/capi/unittest_capi_service_agent_client.cc

If called service-destroy function, do not free allocated handle if an error from dbus or database is raised.

[Service] do not free handle in error case

---

meson.build

This patch fixes build errors because of a missing header file, 'nnstreamer_internal.h', which should be included in the build dependencies by meson.
```bash
$ sudo apt install nnstreamer-dev
$ meson build
$ ninja -C build
ninja: Entering directory `build'
...
../c/src/ml-api-inference-single.c:18:10: fatal error: nnstreamer_internal.h: No such file or directory
18 | #include <nnstreamer_internal.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
...
```

Meson: Add a missing build dependency, 'nnstreamer-internal'

---

daemon/gdbus-util.c
daemon/includes/gdbus-util.h
daemon/pipeline-dbus-impl.cc
tests/capi/unittest_capi_service_agent_client.cc

- Move pipeline related code in gdbus-util to proper src.
- Let std::exception catch those runtime errors.
- Remove unnecessary code in service api test

[CodeClean] Remove unnecessary code in ml-agent

---

daemon/meson.build
tests/meson.build

The changes in https://github.com/nnstreamer/api/commit/2b1df86097d7f94496e7990f68f3495a2b55a4a0 make two sets of object files for the 'machine-learning-agent' and 'machine-learning-agent-test' executables, which leads to the wrong code coverage ratio for the ml-agent daemon source files. This patch fixes it.
FYI, a list of ```gcno``` files are as follows:
```
./build/daemon/machine-learning-agent.p/service-db.cc.gcno
./build/daemon/machine-learning-agent.p/pipeline-dbus-impl.cc.gcno
./build/daemon/machine-learning-agent.p/meson-generated_.._model-dbus.c.gcno
./build/daemon/machine-learning-agent.p/model-dbus-impl.cc.gcno
./build/daemon/machine-learning-agent.p/gdbus-util.c.gcno
./build/daemon/machine-learning-agent.p/pkg-mgr.c.gcno …
```

Meson/LCOV: Fix wrong code coverage ratio for ml-agent sources

---

c/src/ml-api-common.c
c/src/ml-api-inference-single.c
c/src/ml-api-internal.h
tests/capi/unittest_capi_inference_single.cc

This patch adds input and output ranks to ml_single. 
Input and output ranks are used when user explicitly sets rank property.
Related to https://github.com/nnstreamer/api/pull/241#issuecomment-1489867402

[Single] Add input and output ranks @open sesame 4/3 15:31

---

c/src/ml-api-common.c

When calling get-dimension(), fill remained dim - default dim is 1.

[C-Api] fill dim (default 1)

---

c/src/ml-api-common.c

Because of native TC failure, this patch reverts the fill dim (default 1) commit.

[C-Api] Revert fill dim (default 1) commit

---

c/src/ml-api-common.c

This patch fixes the order of ml_tensors_info_set_tensor_dimension. 
If tensors_info is not extended, user may regard dimension array's length to 4.

[C-API] Fix set tensor dimension order @open sesame 04/14 11:14

---

c/src/meson.build
c/src/ml-api-service-agent-client.c
meson.build
packaging/machine-learning-api.spec

In a Tizen application context,
- `ml_service_model_register` fill app_info column. RPK cannot call this API, so the value of key `is_rpk` is always false.
- `ml_service_model_get*` APIs should parse the app_info and update the path in case of models from 'RPK'.

[service/model] Check and parse app_info of tizen application (the caller)

---

daemon/pkg-mgr.cc

- Use g_autofree gchar to prevent memleak;

[CodeClean] Fix memleak in pkgmgr

---

daemon/pkg-mgr.cc
tests/meson.build
tests/mock/meson.build
tests/mock/mock_package_manager.c
tests/mock/mock_package_manager.h

This patch adds helper functions for the emulation of Tizen's Package Manager APIs and utilities for unit test cases of ML Agent Service APIs.

Tests/PkgMgr: Add functions for emulation of Tizen's Pkg Manager APIs @open sesame 04/20 21:53

---

c/src/meson.build
c/src/ml-api-service-agent-client.c
c/src/ml-api-service-common.c
daemon/includes/meson.build
daemon/includes/ml-agent-dbus-interface.h
daemon/meson.build
daemon/ml-agent-dbus-interface.c
packaging/machine-learning-api.spec
tests/capi/meson.build
tests/daemon/meson.build
tests/dbus/meson.build
tests/meson.build

This patch defines APIs of the ML Agent Daemon, whose backend is GDBus, and exports them to the outer space of the daemon so that the tightly coupled dependency between the libcapi-ml-service and daemon is eliminated.

MLAgent: Introduce libml-agentd

---

daemon/meson.build
tests/capi/meson.build
tests/daemon/meson.build
tests/daemon/unittest_service_db.cc
tests/meson.build

This patch applies a simple workaround to increase the line coverage of the 'service-db.cc' file.

Meson/LCOV: Apply a workaround to increase lcov of 'service-db.cc

---

daemon/ml-agent-dbus-interface.c

- Add missing header <errno.h> to the source file.

[build] Add missing errno.h in ml-agent-dbus-interface.c

---

tests/capi/unittest_capi_inference_single.cc

Set `is-updatable` prop of single test
*line coverage: 80.1%

[TEST] Set `is-updatable` prop of single test

---

tests/capi/unittest_capi_service_agent_client.cc

- Add an erroneous pipeline launch case with invalid tensor_filter
- This will increase the line coverage of pipeline-dbus-impl.cc slightly

[test] Add a negative testcase for ml_service_launch_pipeline

---

packaging/machine-learning-api.spec
tests/daemon/meson.build
tests/daemon/unittest_gdbus_util.cc

This patch adds unit test cases for the helper functions in the gdbus-util.c file.

Tests: Add test cases for gdbus-util

---

c/src/ml-api-inference-pipeline-internal.h

This patch adds a missing internal header, 'nnstreamer.h', which defines data structures and types required by the
'ml-api-inference-pipeline-internal.h' file.

API/C: Add the missing header to the pipeline-internal header file

---

daemon/model-dbus-impl.cc
daemon/pipeline-dbus-impl.cc
daemon/pkg-mgr.cc
daemon/service-db.cc
tests/capi/unittest_capi_datatype_consistency.cc
tests/capi/unittest_capi_inference.cc
tests/capi/unittest_capi_inference_latency.cc
tests/capi/unittest_capi_inference_nnfw_runtime.cc
tests/capi/unittest_capi_inference_single.cc
tests/capi/unittest_capi_service_agent_client.cc
tests/daemon/unittest_gdbus_util.cc
tests/daemon/unittest_ml_agent.cc
tests/daemon/unittest_service_db.cc

This patch applies .clang-format to all of the .cc files, which are source files written in C++.
find . -name "*.cc" -exec clang-format-15 --style=file:.clang-format {} \;

Formatting/CC: Apply .clang-format to the C++ source files @open sesame 05/02 19:25

---

.clang-format

clang-format, ignore line-comment length.

[clang-format] line-comment length

---

daemon/pipeline-dbus-impl.cc

When the out parameter type is set to "s" (which means a string type value), it should not be a NULL value. This patch fixes such a case in the DBus callback implementation for the pipeline.

Daemon/DBus: Replace NULL with "" for the DBus out parameters

---

packaging/machine-learning-api.spec
packaging/run-unittest.sh

- Exclude 'ml-api-common-tizen-feature-check.c' and 'ml-api-inference-tizen-privilege-check.c' from the coverage report.
- Change test directory before running the tests.
```
Error:
[DEBUG]:[ RUN      ] [mMLAgentTest.call_method
Error : GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.tizen.machinelearning.service was not provided by any .service files
[DEBUG]:../tests/daemon/unittest_ml_agent.cc:87: Failure
```

[Tizen] Update coverage auto measurement script

---

c/src/ml-api-inference-pipeline.c

- Free GstTensorsConfig using gst_tensors_config_free
- Initialize ml_tensors_info_s before set a new one

[fix] Fix mem leak in pipeline API @open sesame 6/14 14:43

---

daemon/meson.build
daemon/ml-agentd.pc.in
packaging/machine-learning-api.spec

This PR adds a pkg-config file that provides details for using the Machine Machine Learning Agent service interfaces and includes it in the Tizen package, libmachine-learning-agent-devel.

Daemon/Meson: Add a pkg-config file for ml-agentd

---

daemon/model-dbus-impl.cc

This patch adds GStreamer initialization procedure into init_model_module. Without the initialization, D-Bus interfaces for the models inproperly work.

Daemon/Model: Add missing gst initialization

---

c/src/ml-api-common.c
c/src/ml-api-inference-single.c
c/src/ml-api-internal.h
c/src/ml-api-service-query-client.c

- Use ml_option API rather than accessing internal structure.
- Declare ml_info and related enum and structures. And add internal functions for create, destroy, set, get.
- Replace ml_option_s with the new internal structure in ml_option API.

[option] Use ml_option_get to get value from ml_option_h

---

c/include/ml-api-common.h
c/include/ml-api-service.h
c/src/ml-api-common.c
c/src/ml-api-internal.h
c/src/ml-api-service-agent-client.c
tests/capi/unittest_capi_service_agent_client.cc

- Define `ml_information_h` and `ml_information_list_h`.
- Add related APIs
`ml_information_(destroy/get)`
`ml_information_list_(destroy/length/get)`
- Replace ml_option with ml_information in service/model APIs
- Since the signature of APIs (`ml_service_model_get*`) are changed, fix related test code.

[ACR][common/service] Add APIs for ml_information_h and ml_information_list_h

---

daemon/service-db.cc
tests/daemon/unittest_service_db.cc

1. Get resource info with insertion order.
2. We do not neet to export key from service-db. 
Add common json info to get the data from db and hide key from json info.

[Service] data from ml-service

---

tests/capi/unittest_capi_service_agent_client.cc

Set valid handle name in testcase - ml-information handle for model and resource API.

[Service/Test] valid ml-information handle

---

c/src/ml-api-common.c
c/src/ml-api-inference-internal.c
tests/capi/unittest_capi_inference.cc
tests/capi/unittest_capi_inference_nnfw_runtime.cc
tests/capi/unittest_capi_inference_single.cc

This patch removes padded value of dimensions.
Dimension in ml_tensor_info_s is 0 by default.
related to : https://github.com/nnstreamer/nnstreamer/pull/4111

[C-API] remove padded value of dimensions (0-init) @open sesame 08/17 11:02

---

c/src/ml-api-service-query-client.c

Resource leak occurs after ml_tensor_get_count() failure
- need to free ml_tensors_data_h
- change function call order to fix leak

[Coverity] Fix coverity issue

---

c/src/meson.build
c/src/ml-api-remote-service.c
c/src/ml-api-service-common.c
c/src/ml-api-service-private.h
meson.build
packaging/machine-learning-api.spec
tests/capi/meson.build
tests/capi/unittest_capi_remote_service.cc

- Add the function that registers remote service such as NN models, pipeline description and etc.
- Register pipeline description
- Add unittest to register pipeline

[Service] Add remote service register function @open sesame 08/29 16:31

---

tests/capi/unittest_capi_datatype_consistency.cc
tests/capi/unittest_capi_inference.cc

Code clean and fix error case, now rank limit of nnstreamer is changed to 16.

[Test] cleanup testcases @open sesame 09/08 17:48

---

c/src/ml-api-remote-service.c

Let's use safer form of the sprintf() function.

[Coverity] Use snprintf instead of sprintf

---

c/src/ml-api-service-agent-client.c

error param should be paased to 'json_parser_load_from_data' since error_report acess to error message.
* Cherry-pick from main branch: https://github.com/nnstreamer/api/commit/18913e2461db6c7ba08f31ecb27364a1e77db9cd

[PATCH] fix svace issue.

---

c/src/ml-api-remote-service.c

[Service] Check return value

---

c/src/ml-api-remote-service.c

Fix resource leak reported by coverity

[Coverity] Fix resource leak

---

packaging/machine-learning-api.spec

Disable nnfw by default
- To avoid armcl dependency problem on arm arch.

[Tizen] Disable nnfw by default @open sesame 09/21 13:35

---

c/include/nnstreamer-tizen-internal.h
c/src/meson.build
c/src/ml-api-service-private.h
c/src/ml-api-service-remote.c
tests/capi/unittest_capi_remote_service.cc

1. Update ml-remote function name, prefix 'ml_service'.
2. Hide internal enum and struct.

[CodeClean] function name

---

c/src/ml-api-service-agent-client.c
c/src/ml-api-service-common.c
c/src/ml-api-service-private.h
c/src/ml-api-service-query-client.c
c/src/ml-api-service-remote.c
meson.build

Prevent error case if nns-edge dependency does not exists. Add internal function to release ml-svc handle.

[CodeClean] internal function to release svc handle

---

tests/capi/unittest_capi_inference.cc

This is a trivial fix to silence sign-compare warnings in a unit test case for inference C-APIs.
/usr/src/googletest/googletest/include/gtest/gtest.h:1545:11: error: comparison of integer expressions of different signedness: ‘const unsigned int’ and ‘const int’ [-Werror=sign-compare]
```
1545 |   if (lhs == rhs) {
|       ~~~~^~~~~~ 
cc1plus: all warnings being treated as errors
```

Tests/CAPI: Fix trivial sign-compare warnings

---

daemon/pkg-mgr.cc

1. Update 'activate' flag from json when registering new model info from res-pkg.
2. Allow null description in json, description string is not mandatory field.
3. Fix log message, hide app info string.

[Service] active flag from json

---

c/src/ml-api-inference-internal.c

We implemented 0-init dimension in nnstreamer.
If dim value at index of old rank limit (4) is not 0, it is extended.

[Util] extended dim of 0-initialized

---

daemon/pkg-mgr.cc

Parse json file and update model/pipeline/resource data when installing res-pkg.

[Service] parse json for database update

---

c/src/ml-api-common.c
c/src/ml-api-inference-pipeline-internal.h
c/src/ml-api-inference-pipeline.c
c/src/ml-api-inference-single.c
tests/capi/unittest_capi_inference.cc
tests/capi/unittest_capi_inference_nnfw_runtime.cc
tests/capi/unittest_capi_inference_single.cc
tests/capi/unittest_capi_remote_service.cc
tests/capi/unittest_capi_service_agent_client.cc

1. Create tensors-info handle before calling sink callback.
2. We do not need to use ml-info in pipeline elem struct. Use gst-info instead.

[C-Api/Pipeline] create handle before calling sink callback

---

c/include/nnstreamer-tizen-internal.h
c/src/ml-api-service-remote.c
tests/capi/unittest_capi_inference.cc
tests/capi/unittest_capi_remote_service.cc

Add a path to save the received model file to the ml-option.
Signed-off-by: gichan2-jang <gichan2.jang@samsung.com>

[Remote-service] Add a path to save the model  @open sesame 11/17 16:24

---

c/src/ml-api-service-remote.c

Let's generate edge handle ID automatically by default.
The user also set edge ID using ml_option_set().
Signed-off-by: gichan2-jang <gichan2.jang@samsung.com>

[ml-service] Set nns-edge handle ID.

---

tests/capi/unittest_capi_datatype_consistency.cc

Code clean, now max number of tensors in nnstreamer and api repo is same.
Restore old test to compare the max tensors.

[Test] restore test

---

c/meson.build
c/src/ml-api-inference-tizen-privilege-check.c
packaging/machine-learning-api.spec

Code clean, update dependency for each tizen features.

[Build/Tizen] dependency of tizen feature

---

c/src/meson.build
c/src/ml-api-service-private.h
c/src/ml-api-service-remote.c
daemon/meson.build
meson.build
tests/capi/meson.build
tests/capi/unittest_capi_remote_service.cc
tests/capi/unittest_capi_service_agent_client.cc

Prepare deleting ml-agent from api repo, set dependency to ml-agent and remove unnecessary line.

[CodeClean] dependency to ml-agent

---

.TAOS-CI/.gbs.conf

Change gbs repo from latest to reference.
the default location of the ".gbs.conf" file has the highest priority.

Change gbs repo from latest to reference

---

c/src/ml-api-inference-single.c

- Destroy ml_tensors_info_h in ml_single_close
- Call gst_tensors_info_free
* Backporting: https://github.com/nnstreamer/api/commit/9307dc7fbb5f79ed9d54a6e4555b275046467f65

[Fix] Fix mem leak in Single API

---

.TAOS-CI/.gbs.conf

- Change url from Tizen -> Tizen-7.0 for TAOS-CI gbs build test.

[lts][gbs] Fix gbs repo url to Tizen-7.0

---

tests/capi/unittest_capi_inference_single.cc

In testcase of ArmNN, remove unnecessary tensor-info and compare dimension after getting info handle from model.

[Test] remove unnecessary info handle

---

daemon/service-db.cc
packaging/machine-learning-api.spec

This patch is a trivial bug fix that adds an omitted build dependency on libtzplatform-config to the Tizen RPM spec file.
CC: @jaeyun-jung 

[Dist/Tizen] Add omitted build dependency on libtzplatform-config

---

c/src/ml-api-inference-single.c

To prevent not-found error, remove space of model path. Also check file existence when validating model files.

[C-Api] remove space of models

---

c/include/ml-api-service.h

Remove unnecessary macro for old API set.
We should update Tizen test later.

[C-Api/Service] remove macro for old API

---

tests/capi/unittest_capi_service_extension.cc
tests/test_models/config/config_pipeline_imgclf_key.conf
tests/test_models/config/config_single_imgclf_key.conf

We can register new model (or pipeline) using ml-service API.
Add test for registered key from ml-agent.

[Test/Service] add new test to get model from ml-agent

---

packaging/run-unittest.sh

Fix tizen auto coverage measurement failure.
Use default root path instead of environment variable. The model path of the config file is hard coded, so the wrong model path is passed to ml-service.
config_single_add.conf
```
{
"single" :
{
"framework" : "tensorflow-lite",
"model" : ["../tests/test_models/models/add.tflite"]
}
}
```

[Tizen] Update unittest build script

---

.github/workflows/android.yml
java/build-nnstreamer-android.sh

This patch replaces TAOS-CI script for android build.
This PR requires https://github.com/nnstreamer/nnstreamer-android-resource/pull/41

[action] replace TAOS-CI script for android build in API Level 34 @open sesame 04/04 20:31

---

tests/capi/unittest_capi_inference.cc
tests/capi/unittest_capi_inference_single.cc

This is a trivial patch that adds more negative test cases for the inference C-APIs.

Tests/CAPI: Add more negative test cases

---

java/build-nnstreamer-android.sh

nnstreamer-android-resource directory is changed not to download using scripts.
So it shouldn't be removed.

[android] do not remove android-resource dir

---

c/src/ml-api-service-agent-client.c

To remove unnecessary dbus-sig, add force-delete flag in ml-agent interface.

[C-Api/Service] change ml-agent param

---

c/include/ml-api-service.h

ml_service_start_pipeline is modified to ml_service_start from Tizen 7.0, change since_tizen tag.

[Tizen] Change @since_tizen tag for ml-service-start/stop

---

java/android/nnstreamer/src/main/AndroidManifest.xml

- Recent android requires specifying certain shared libraries.
- libOpenCL.so is needed to check functionality of GPU delegates.
REF: https://github.com/tensorflow/tensorflow/issues/48001#issuecomment-1386958937

[android] Set libOpenCL.so dependency in AndroidManiest.xml

---

java/android/nnstreamer/src/main/AndroidManifest.xml

This patch fixes typo in AndroidManifest.
uses-libaray -> uses-library

[android] fix typo in AndroidManifest

---

.github/workflows/android.yml

This patch changes the way to set java version in github action.

[action] use action/setup-java instead of export JAVA_HOME

---

packaging/machine-learning-api.spec

Update spec to enable ONNX runtime and training-offloading from Tizen 9.0.

[Build] onnx-runtime/training-offloading from tizen 9.0

---

c/src/ml-api-service-training-offloading.c

Code clean, check null pointer of train-offloading handle before using it.

[CodeClean] check null before using handle

---

c/src/ml-api-service-agent-client.c
c/src/ml-api-service-extension.c
c/src/ml-api-service-offloading.c
c/src/ml-api-service-private.h
c/src/ml-api-service-training-offloading.c
c/src/ml-api-service.c

Changed to check the existence of the jsom member before getting the value.
This change reduces unnecessary error messages that occur when setting optional ml information.

[ml-service] Get string member from json object

---

packaging/machine-learning-api.spec

This patch disables the nnfw and onnxruntime features for the movable project.
2. Run test: [ ]Passed [ ]Failed [X]Skipped

[Spec] Disable some features for movable project

---

c/src/ml-api-service-query-client.c
tests/capi/unittest_capi_service_offloading.cc

The ml-service-query-client test sometimes fails.
Let's revert the change and repeat the tests.
Related issue: https://github.com/nnstreamer/api/issues/421

[ml-service] Change caps prop to caps filter of appsrc @open sesame 05/27 12:33

---

c/src/ml-api-service.c

- Clearly state that the json parse error with INVALID_PARAM value

[service] Fix error value and log in ml_service_new

---

java/build-nnstreamer-android.sh

- Fix the invalid path for flatbuf and paho-mqtt-c tar.xz files

[android] Fix typo in build script

---

java/android/nnstreamer/build.gradle
java/android/nnstreamer/src/main/AndroidManifest.xml
java/android/nnstreamer/src/main/jni/Android-snpe.mk
java/build-nnstreamer-android.sh

Add SNPE SDK v2 support:
- Let `build-nnstreamer-android.sh` copy proper files from SNPE SDK
- Let ndk build with tensor_filter_snpe.cc or ..._v1.cc with proper headers and flags
- Link `libcdsprpc.so`
REF: https://source.android.com/docs/core/permissions/namespaces_libraries#specify-native-library-dependencies
Proper android app settings:
- Recent AGP requires `useLegacyPackaging = true` in build.gradle
REF: https://developer.android.com/build/releases/past-releases/agp-4-2-0-release-notes#compress-native-libs-dsl

[Android] Support SNPE SDK v2

---

tests/capi/unittest_capi_service_training_offloading.cc

- The pipeline for training offloading is designed to perform training and validation, but nntrainer creates a model after finishing training, therefore validation time is necessary.

[ml-service] Fix bug in unittest_capi_service_training_offloading

---

.github/workflows/android.yml
java/android/nnstreamer/src/main/jni/Android-tensorflow-lite.mk
java/build-nnstreamer-android.sh

- Add tflite v2.16.1 support for android
- Deprecates old versions and leaves only v2.8.1 and v2.16.1
- In github actions, Enable tflite for x86_64 (for emulators) / Disable tflite for armeabi-v7a
See also https://github.com/nnstreamer/nnstreamer-android-resource/pull/44

[android] Support tflite v2.16.1

---

java/android/nnstreamer/src/main/jni/Application.mk

This patch changes the c++ version to 17 in the jni files. meson.build also uses cpp_std=c++17.
https://github.com/nnstreamer/nnstreamer/issues/4493

[Android] Use c++17 for ndk-build

---

java/android/nnstreamer/src/main/jni/Android.mk

As TensorFlow Lite no longer supports 32-bit architectures, this patch revises Android.mk according to this change.

JNI/Android: Deprecate support TFLite for armeabi-v7a

---

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
java/android/nnstreamer/src/main/assets/README.txt

- Recent Android do not allow to use `getExternalStorageDirectory`.
- Let's copy test related files to app's internal directory from assets. Required files are listed in the README.txt file

[android] Let test related files be copied to app's internal directory from assets.

---

java/android/nnstreamer/src/main/jni/Android.mk

Since SNPEv2 supports Android only for aarch64, this patch specifies the ABI for it in the Android.mk file.

JNI/Android: Specify an ABI that SNPE supports

---

java/android/nnstreamer/build.gradle
java/android/nnstreamer/src/main/jni/Android-tensorflow-lite.mk
java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c
java/build-nnstreamer-android.sh

- Fix build scripts (*.mk files and build.gradle) for TFLite QNN Delegate.
- Fix build-nnstreamer-android.sh to build TFLite QNN Delegate support.
- Init tflite filter with android context
This requires https://github.com/nnstreamer/nnstreamer/pull/4502 to be merged.

[Android] Build TFLite QNN Delegate

---

c/src/ml-api-service-extension.c

- There are valid pipelines consists of no appsrc/tensor_sink.
- Let `ml_service_new` allow those cases.

[service] Allow no input / no output node in ext/conf

---

c/src/ml-api-service-agent-client.c
c/src/ml-api-service-extension.c
c/src/ml-api-service-extension.h
c/src/ml-api-service-offloading.c
c/src/ml-api-service-offloading.h
c/src/ml-api-service-private.h
c/src/ml-api-service-query-client.c
c/src/ml-api-service-training-offloading.c
c/src/ml-api-service-training-offloading.h
c/src/ml-api-service.c
tests/capi/unittest_capi_service_offloading.cc
tests/capi/unittest_capi_service_training_offloading.cc

To distinguish between internal and public APIs, prepend `_` to the internal APIs.

[Refactor] Prepend `_` to  internal API name

---

.github/actions/android-build/action.yml
.github/workflows/android.yml
.github/workflows/daily-build-android.yml

- Separate android build common part to composite action.
- Run android daily build
- Generate javadoc

[Actions] Add android daily build

---

c/src/ml-api-internal.h

Code clean, fix typo in internal header file.

[CodeClean] fix typo

---

c/include/ml-api-common.h
c/src/ml-api-inference-single.c

- Add enum for Qualcomm QNN (Qualcomm® AI Engine Direct)
- Its being prepared in Tizen and nnstreamer.

[single] Add ML_NNFW_TYPE enum for QNN

---

java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestCustomFilter.java
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestPipeline.java
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestSingleShot.java
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestTensorsInfo.java
java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/TensorsInfo.java

- Fix test for max rank dimension
- Let `getDimension` returns rank-aware array
: `[3, 224, 224, 1]` rather than `[3, 224, 224, 1, 0, 0, ..., 0]`
- Use rank-aware dimension in android tests
- Use `getRootDirectory` instead of `getExternalStorageDirectory` for android tests.

[android] Fix android tests handling tensor dimension

---

java/android/nnstreamer/build.gradle
java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/NNStreamer.java
java/android/nnstreamer/src/main/jni/Android-qnn.mk
java/android/nnstreamer/src/main/jni/Android.mk
java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c
java/build-nnstreamer-android.sh

- Add ndk-build/makefile to build qnn subplugin.
- Add Java enum type for qnn and fIx script to build qnn subplugin.
This requires https://github.com/nnstreamer/nnstreamer/pull/4566.

[android] Build qnn subplugin

---

java/android/nnstreamer/src/main/jni/Android-llama2c-prebuilt.mk
java/android/nnstreamer/src/main/jni/Android-llama2c.mk
java/android/nnstreamer/src/main/jni/Android.mk

This patch adds the .mk scripts to enable ndk-build support for llama2.c.

JNI/Android: Add .mk files for ndk-build support of llama2.c

---

c/include/nnstreamer.h

This patch fixes the typo in code example.
Signed-off-by: Sangjung Woo [sangjung.woo@samsung.com](mailto:sangjung.woo@samsung.com)
2. Run test: [ ]Passed [ ]Failed [X]Skipped

[Doc] Fix the typo in example code

---

c/include/meson.build
c/include/ml-api-staging.h
packaging/machine-learning-api.spec

Staging header will be added to Tizen 7.0.
Add empty staging header file to prevent build errors for users using the header file.

[ml-service] Add staging header to prevent build error

---

.github/workflows/daily-build-gbs.yml
.github/workflows/gbs_build.yml

From Tizen 10, i586 is removed.
Let's remove the i586 build.

[Tizen] Remove i586 build test

---

java/android/nnstreamer/src/main/jni/Android-nnstreamer.mk
java/android/nnstreamer/src/main/jni/Android.mk

- Let android utilizes nnstreamer's orc code (tensor_transform).
- Requires https://github.com/nnstreamer/nnstreamer/pull/4651 to be merged.

[android] Let it build and use orc from nnstreamer

---

.github/actions/gitpush/action.yml

The method of getting the diff of git is failing now.
Changed to check code diff by filtering the result.
Failed job: https://github.com/nnstreamer/api/actions/runs/12400628640/job/34618240664
After this patch: https://github.com/gichan-jang/api/actions/runs/12409355776/job/34642806472
* I'm sorry that I didn't check the behavior of the daily build accurately in the last patch.

[Action] Change how to detect code change

---

java/build-nnstreamer-android.sh

Fix invalid path to compress build result after updating ndk version.

[Build/Android] compressing build result

---

c/src/ml-api-service-training-offloading.c

- Fix typo `replce` into `replace`, complained by CI.

[trivial] Fix typos in internal func name

---

java/android/nnstreamer/build.gradle
java/android/nnstreamer/src/main/jni/Android-nnfw.mk
java/android/nnstreamer/src/main/jni/Android-qnn.mk
java/android/nnstreamer/src/main/jni/Android-snpe.mk
java/android/nnstreamer/src/main/jni/Android-tensorflow-lite.mk
java/android/nnstreamer/src/main/jni/Android.mk
java/build-nnstreamer-android.sh

Set common path for external libraries on android build.
This PR will build android library including same external files - SNPE, QNN, and TF-lite QNN delegate.

[Android] common path for external libs

---

java/build-nnstreamer-android.sh

Remove unnecessary line for deleting nnstreamer version header when building android library.

[Android] header for nns version

---

java/android/nnstreamer/src/main/jni/nnstreamer-native-singleshot.c

Fix invalid param when releasing converted string in native function.

[Android] invalid param

---

c/src/ml-api-inference-single.c

- Let single API handle flexible filter.

[api] Let single handle flexible filter

---

java/android/nnstreamer/src/androidTest/assets/README.txt
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestCommon.java
java/android/nnstreamer/src/androidTest/java/org/nnsuite/nnstreamer/APITestMLService.java
java/android/nnstreamer/src/main/java/org/nnsuite/nnstreamer/MLService.java
java/android/nnstreamer/src/main/jni/Android.mk
java/android/nnstreamer/src/main/jni/nnstreamer-native-api.c
java/android/nnstreamer/src/main/jni/nnstreamer-native-internal.h
java/android/nnstreamer/src/main/jni/nnstreamer-native-service.c
java/build-nnstreamer-android.sh

Add new class and interface for ml-service api.

[Android] class for ml-service

---

c/src/ml-api-common.c
c/src/ml-api-internal.h
tests/capi/unittest_capi_inference_single.cc

Add new function to iterate key-value pairs in ml-information.

[C-Api] function to iterate ml-information
